/**
 * Making a ref from the product's template in one pass: a number, an optional name, and a
 * decision about each image and narration the template uses (keep it, generate it again from
 * an edited text, upload a replacement, or pick one of the template's uploads).
 *
 * The server copies the template and applies the decisions (`POST /:id/refs`). Files chosen
 * to upload are stored in the new ref afterwards and bound there, and anything marked to
 * regenerate is generated by an ordinary speech and images run of the new ref, so each one is
 * traced in its history. The derivations live in `ref-plan.ts`.
 */
import { useEffect, useRef, useState } from "react";
import type {
  ActivityDetail,
  ActivityRecord,
  RefNumberSuggestion,
  UploadedMedia,
  VoiceOption,
} from "@prismshadow/penguin-server/api";
import { ApiError, apiFetch } from "../../api/client";
import { Button, labelButtonClass } from "../../components/ui/button";
import { ChipGroup } from "../../components/ui/chip-group";
import { HiddenFileInput } from "../../components/ui/hidden-file-input";
import { InfoPopover } from "../../components/ui/info-popover";
import { Input, Textarea } from "../../components/ui/input";
import { Select } from "../../components/ui/select";
import { apiErrorText } from "../../lib/api-error";
import { S } from "../../lib/strings";
import { toneStrip } from "../../lib/tone";
import { ImagePreview } from "./image-preview";
import { MediaLibraryModal } from "./media-library-modal";
import { MediaPlayer } from "./media-player";
import { UPLOAD_ACCEPT, uploadKindFor } from "./media-library";
import {
  REF_DESCRIPTION_MAX,
  REF_SCRIPT_MAX,
  blockers,
  boundSource,
  decisions,
  groupRows,
  keepAll,
  needsGeneration,
  planRows,
  refNumberFrom,
  regenerateAllImages,
  sceneOrder,
  setAction,
  setFileName,
  setLibraryPath,
  setText,
  voiceForAll,
  type RefPlanBlocker,
  type RefPlanRow,
  type RowAction,
} from "./ref-plan";

const HEAD =
  "border-b border-gray-100 bg-gray-50 text-left text-xs text-gray-500 dark:border-gray-800 dark:bg-gray-900/60 dark:text-gray-400";
const TH = "whitespace-nowrap px-3 py-2 font-medium";
const TD = "px-3 py-2 align-top";
const ACTIONS: readonly RowAction[] = ["keep", "regenerate", "upload", "library"];

/** A blocker in the author's words. */
function blockerText(blocker: RefPlanBlocker): string {
  const words = S.activities.createRef.blockers;
  switch (blocker.code) {
    case "missingRefNum":
      return words.missingRefNum;
    case "refNumTaken":
      return words.refNumTaken(blocker.refNum);
    case "scriptTooLong":
      return words.scriptTooLong(blocker.key, REF_SCRIPT_MAX);
    case "descriptionTooLong":
      return words.descriptionTooLong(blocker.key, REF_DESCRIPTION_MAX);
    default:
      return words[blocker.code](blocker.key);
  }
}

/** Why the server refused, in the author's words where the reason is one of ours. */
function createErrorText(cause: unknown): string {
  const reasons = S.activities.createRef.errors as Record<string, string | undefined>;
  return (cause instanceof ApiError && reasons[cause.code]) || apiErrorText(cause);
}

function typeName(row: RefPlanRow): string {
  const types = S.activities.createRef.types;
  if (row.narration) return types.narration;
  if (row.type === "audio") return types.sound;
  return types[row.type];
}

/** Store a chosen file as an upload of an activity, and hand back its reference. */
async function uploadTo(endpoint: string, file: File): Promise<UploadedMedia> {
  const buffer = new Uint8Array(await file.arrayBuffer());
  let binary = "";
  for (let index = 0; index < buffer.length; index += 0x8000)
    binary += String.fromCharCode(...buffer.subarray(index, index + 0x8000));
  return apiFetch<UploadedMedia>(`${endpoint}/media-uploads`, {
    method: "POST",
    body: { name: file.name, dataBase64: btoa(binary) },
  });
}

export function CreateRefView({
  base,
  endpoint,
  template,
  editable,
  voices,
  uploads,
  uploadsLoading,
  agents,
  defaultAgent,
  onIdentity,
  onOpenAssessment,
  onCreated,
}: {
  /** The project's activities API path. */
  base: string;
  /** The template's API path. */
  endpoint: string;
  template: ActivityDetail;
  editable: boolean;
  voices: readonly VoiceOption[];
  /** The template's uploads, which a row may pick from. */
  uploads: readonly UploadedMedia[];
  uploadsLoading: boolean;
  /** The Penguin agents that can generate speech and images. */
  agents: readonly { agentId: string; name?: string | null }[];
  defaultAgent: string;
  onIdentity: (record: ActivityRecord) => void;
  onOpenAssessment: () => void;
  /** The ref exists; `problem` says what failed after it was made, if anything did. */
  onCreated: (detail: ActivityDetail, problem: string | null) => void;
}) {
  const words = S.activities.createRef;
  const manifest = template.draft.mediaPlan?.manifest;
  const languages = Object.keys(manifest?.assets ?? {});
  const [language, setLanguage] = useState(
    languages.includes("en-US") ? "en-US" : (languages[0] ?? "en-US"),
  );
  const order = sceneOrder(template.draft.spec);
  const [rows, setRows] = useState<RefPlanRow[]>(() => planRows(manifest, language, order));
  const [suggestion, setSuggestion] = useState<RefNumberSuggestion | null>(null);
  const [refText, setRefText] = useState("");
  const typed = useRef(false);
  const [name, setName] = useState("");
  const [voice, setVoice] = useState("");
  const [agentChoice, setAgent] = useState("");
  const agent = agents.some((entry) => entry.agentId === agentChoice)
    ? agentChoice
    : agents.some((entry) => entry.agentId === defaultAgent)
      ? defaultAgent
      : (agents[0]?.agentId ?? "");
  const files = useRef(new Map<string, File>());
  const [picking, setPicking] = useState<RefPlanRow | null>(null);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [marking, setMarking] = useState(false);
  const alive = useRef(true);
  useEffect(() => {
    alive.current = true;
    return () => {
      alive.current = false;
    };
  }, []);

  useEffect(() => {
    let cancelled = false;
    apiFetch<RefNumberSuggestion>(`${endpoint}/refs/next-number`)
      .then((value) => {
        if (cancelled || typeof value?.refNum !== "number") return;
        setSuggestion(value);
        if (!typed.current) setRefText(String(value.refNum));
      })
      .catch(() => {
        /* The number can still be typed; the server checks it either way. */
      });
    return () => {
      cancelled = true;
    };
  }, [endpoint]);

  const taken = suggestion?.taken ?? [];
  const found = blockers(rows, refText, taken);
  const generate = needsGeneration(rows);
  const canonical = suggestion?.canonical !== false;
  const ready =
    editable &&
    canonical &&
    template.stable &&
    !!manifest &&
    !found.length &&
    !creating &&
    (!generate || !!agent);

  function chooseLanguage(next: string) {
    setLanguage(next);
    files.current.clear();
    setRows(voiceForAll(planRows(manifest, next, order), voice || null));
  }

  async function markStable() {
    setMarking(true);
    setError(null);
    try {
      const record = await apiFetch<ActivityRecord>(`${endpoint}/identity`, {
        method: "PATCH",
        body: { stable: true },
      });
      onIdentity(record);
    } catch (cause) {
      if (alive.current) setError(apiErrorText(cause));
    } finally {
      if (alive.current) setMarking(false);
    }
  }

  async function create() {
    const refNum = refNumberFrom(refText);
    if (refNum === null || !ready) return;
    setCreating(true);
    setError(null);
    let detail: ActivityDetail;
    try {
      detail = await apiFetch<ActivityDetail>(`${endpoint}/refs`, {
        method: "POST",
        body: {
          refNum,
          ...(name.trim() ? { displayName: name.trim() } : {}),
          decisions: decisions(rows, language),
        },
      });
    } catch (cause) {
      if (alive.current) {
        setError(createErrorText(cause));
        setCreating(false);
      }
      return;
    }
    // The ref exists from here on. What follows finishes it; a failure is said, not undone.
    const made = `${base}/${encodeURIComponent(detail.id)}`;
    let problem: string | null = null;
    try {
      const toUpload = rows.filter((row) => row.editable && row.action === "upload");
      if (toUpload.length && detail.draft.mediaPlan) {
        const next = structuredClone(detail.draft.mediaPlan.manifest);
        for (const row of toUpload) {
          const stored = await uploadTo(made, files.current.get(row.key)!);
          const asset = next.assets[language]?.find((entry) => entry.key === row.key);
          if (asset) asset.path = stored.path;
        }
        await apiFetch(`${made}/media`, {
          method: "PUT",
          body: { manifest: next, expectedRevision: detail.draft.contentRevision },
        });
      }
      // Only the language decided here: other languages keep the template's assets and
      // voices, so the chosen voice cannot reach narrations the page never showed.
      if (generate)
        await apiFetch(`${made}/pipeline`, {
          method: "POST",
          body: { agentId: agent, stage: "assets", language, ...(voice ? { voice } : {}) },
        });
    } catch (cause) {
      problem = apiErrorText(cause);
    }
    if (alive.current) setCreating(false);
    onCreated(detail, problem);
  }

  const imageUrl = (key: string) =>
    `${endpoint}/media-image?${new URLSearchParams({
      language,
      assetKey: key,
      expectedRevision: template.draft.contentRevision,
    })}`;

  function current(row: RefPlanRow) {
    if (!row.asset.path) return <span className="text-xs text-gray-500">{words.unbound}</span>;
    if (row.type === "image")
      return <ImagePreview key={imageUrl(row.key)} src={imageUrl(row.key)} description={row.key} />;
    const src = boundSource(row.asset, endpoint);
    if (!src || row.type === "animation")
      return <span className="text-xs text-gray-500">{words.bound}</span>;
    return (
      <MediaPlayer kind={row.type === "audio" ? "audio" : "video"} src={src} label={row.key} />
    );
  }

  function details(row: RefPlanRow) {
    if (row.action === "regenerate")
      return (
        <Textarea
          size="sm"
          rows={3}
          label={row.narration ? words.script : words.description}
          value={row.text}
          disabled={creating}
          onChange={(event) =>
            setRows((previous) => setText(previous, row.key, event.target.value))
          }
        />
      );
    if (row.action === "upload") {
      const kind = uploadKindFor(row.type);
      return (
        <div className="space-y-1">
          <label
            className={`relative inline-flex items-center ${labelButtonClass("secondary", "sm")}`}
          >
            <HiddenFileInput
              aria-label={`${words.chooseFile}: ${row.key}`}
              accept={UPLOAD_ACCEPT[kind]}
              disabled={creating}
              onChange={(event) => {
                const file = event.target.files?.[0];
                event.target.value = "";
                if (!file) return;
                files.current.set(row.key, file);
                setRows((previous) => setFileName(previous, row.key, file.name));
              }}
            />
            {words.chooseFile}
          </label>
          {row.fileName && (
            <p className="break-all text-xs text-gray-500">{words.chosenFile(row.fileName)}</p>
          )}
        </div>
      );
    }
    if (row.action === "library") {
      const chosen = uploads.find((entry) => entry.path === row.libraryPath);
      return (
        <div className="space-y-1">
          <Button size="sm" disabled={creating} onClick={() => setPicking(row)}>
            {words.choose}
          </Button>
          {row.libraryPath && (
            <p className="break-all text-xs text-gray-500">
              {words.chosenUpload(chosen?.name ?? row.libraryPath)}
            </p>
          )}
        </div>
      );
    }
    return null;
  }

  return (
    <section className="space-y-4" aria-labelledby="create-ref-title">
      <h3 id="create-ref-title" className="flex items-center gap-2 text-base font-semibold">
        {words.title}
        <InfoPopover label={words.title}>
          <p>{words.about}</p>
        </InfoPopover>
      </h3>
      {!canonical && (
        <p role="status" className={`rounded-md border p-3 text-xs ${toneStrip.attention}`}>
          {words.notCanonical}
        </p>
      )}
      {canonical && !template.stable && (
        <div
          role="status"
          className={`flex flex-wrap items-center gap-3 rounded-md border p-3 text-xs ${toneStrip.attention}`}
        >
          <span className="min-w-0 flex-1">{words.notStable(template.refNum)}</span>
          {editable && (
            <Button size="sm" disabled={marking} onClick={() => void markStable()}>
              {words.markStable}
            </Button>
          )}
        </div>
      )}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <Input
          size="sm"
          type="number"
          min={0}
          step={1}
          label={words.refNum}
          hint={words.refNumHint}
          value={refText}
          disabled={creating}
          onChange={(event) => {
            typed.current = true;
            setRefText(event.target.value);
          }}
        />
        <Input
          size="sm"
          label={words.name}
          hint={words.nameHint}
          maxLength={64}
          value={name}
          disabled={creating}
          onChange={(event) => setName(event.target.value)}
        />
        {languages.length > 1 && (
          <Select
            size="sm"
            label={words.language}
            value={language}
            disabled={creating}
            onChange={(event) => chooseLanguage(event.target.value)}
          >
            {languages.map((code) => (
              <option key={code} value={code}>
                {code}
              </option>
            ))}
          </Select>
        )}
        {voices.length > 0 && rows.some((row) => row.narration) && (
          <Select
            size="sm"
            label={words.voiceForAll}
            value={voice}
            disabled={creating}
            onChange={(event) => {
              setVoice(event.target.value);
              setRows((previous) => voiceForAll(previous, event.target.value || null));
            }}
          >
            <option value="">{words.voiceUnchanged}</option>
            {voices.map((option) => (
              <option key={option.id} value={option.id}>
                {option.label}
              </option>
            ))}
          </Select>
        )}
      </div>
      <div className="flex flex-wrap items-center gap-2">
        <Button
          size="sm"
          disabled={creating || !rows.length}
          onClick={() => {
            setVoice("");
            files.current.clear();
            setRows((previous) => keepAll(previous));
          }}
        >
          {words.keepAll}
        </Button>
        <Button
          size="sm"
          disabled={creating || !rows.some((row) => row.type === "image")}
          onClick={() => setRows((previous) => regenerateAllImages(previous))}
        >
          {words.regenerateImages}
        </Button>
      </div>
      {rows.length > 0 && (
        <div className="overflow-x-auto rounded-lg border border-gray-200 dark:border-gray-800">
          <table className="w-full text-sm">
            <thead>
              <tr className={HEAD}>
                <th className={TH}>{words.columns.asset}</th>
                <th className={TH}>{words.columns.type}</th>
                <th className={TH}>{words.columns.current}</th>
                <th className={TH}>{words.columns.action}</th>
                <th className={TH}>{words.columns.details}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-gray-800/60">
              {groupRows(rows).flatMap((group) =>
                group.rows.map((row) => (
                  <tr key={row.key}>
                    <td className={TD}>
                      <span className="block break-all font-medium">{row.key}</span>
                      <span className="block text-xs text-gray-500">
                        {row.scenes.length ? words.scenes(row.scenes.join(", ")) : words.noScene}
                      </span>
                    </td>
                    <td className={`${TD} whitespace-nowrap text-xs`}>{typeName(row)}</td>
                    <td className={`${TD} min-w-40`}>{current(row)}</td>
                    <td className={TD}>
                      {row.editable ? (
                        <ChipGroup
                          label={words.actionsFor(row.key)}
                          value={row.action}
                          disabled={creating}
                          onChange={(action) =>
                            setRows((previous) => setAction(previous, row.key, action))
                          }
                          options={ACTIONS.map((action) => ({
                            value: action,
                            label: words.actions[action],
                          }))}
                        />
                      ) : (
                        <span className="text-xs text-gray-500">{words.copied}</span>
                      )}
                    </td>
                    <td className={`${TD} min-w-56`}>{row.editable ? details(row) : null}</td>
                  </tr>
                )),
              )}
            </tbody>
          </table>
        </div>
      )}
      <p className="flex flex-wrap items-center gap-2 text-xs text-gray-500">
        {words.assessmentShared(template.refNum)}
        <Button size="sm" variant="ghost" onClick={onOpenAssessment}>
          {words.openAssessment}
        </Button>
      </p>
      {generate && (
        <div className="max-w-xs">
          {agents.length ? (
            <Select
              size="sm"
              label={words.agent}
              value={agent}
              disabled={creating}
              onChange={(event) => setAgent(event.target.value)}
            >
              {agents.map((entry) => (
                <option key={entry.agentId} value={entry.agentId}>
                  {entry.name ?? entry.agentId}
                </option>
              ))}
            </Select>
          ) : (
            <p className="text-xs text-gray-500">{words.noAgent}</p>
          )}
        </div>
      )}
      {found.length > 0 && (
        <div role="status" className={`rounded-md border p-3 text-xs ${toneStrip.danger}`}>
          <p className="font-medium">{words.blockersTitle}</p>
          <ul className="mt-1 list-disc space-y-0.5 pl-4">
            {found.map((blocker) => (
              <li key={`${blocker.code}:${"key" in blocker ? blocker.key : ""}`}>
                {blockerText(blocker)}
              </li>
            ))}
          </ul>
        </div>
      )}
      {error && (
        <p role="alert" className={`rounded-md border p-3 text-xs ${toneStrip.danger}`}>
          {error}
        </p>
      )}
      {editable && (
        <div className="flex justify-end">
          <Button size="sm" variant="primary" disabled={!ready} onClick={() => void create()}>
            {creating ? words.creating : words.create}
          </Button>
        </div>
      )}
      {picking && (
        <MediaLibraryModal
          media={uploads}
          type={picking.type}
          endpoint={endpoint}
          loading={uploadsLoading}
          localOnly
          onClose={() => setPicking(null)}
          onPick={(path) => {
            setRows((previous) => setLibraryPath(previous, picking.key, path));
            setPicking(null);
          }}
        />
      )}
    </section>
  );
}
