import type { PeakWindows } from "../features/models/model-grouping";

/** Shared dictionary contract for supported translations. */
export type Strings = {
  appName: string;
  activities: {
    mediaLanguage: string;
    noMediaAssets: string;
    boundMedia: string;
    downloadCurrent: string;
    unboundMedia: string;
    usedInScenes: string;
    noSceneUsage: string;
    assetPath: string;
    assetPathHint: string;
    sceneAssets: string;
    workspaceRail: string;
    /** The hierarchy panel, named the way Loom names it. */
    studioTree: {
      label: string;
      rows: Record<
        | "activityScript"
        | "activitySpec"
        | "implementationFeatures"
        | "configurationData"
        | "assessmentData"
        | "moduleDefinition"
        | "audios"
        | "scenes"
        | "activityStats"
        | "unassigned"
        | "mediaLibrary"
        | "history",
        string
      >;
      groups: Record<"image" | "video" | "audio" | "animation", string>;
      fold: (name: string) => string;
      unfold: (name: string) => string;
      needsMedia: string;
    };
    /** What the playing activity reports about itself, under the player. */
    studioPlayer: {
      now: (state: string, scene: string) => string;
      waiting: string;
      tapTargets: string;
      pick: string;
      picking: string;
      opened: (name: string) => string;
      noMatch: (id: string) => string;
      noMedia: string;
      silent: string;
      map: {
        toggle: string;
        scene: string;
        loading: string;
        none: string;
        unreadable: (reason: string) => string;
        leaves: string;
        trigger: { after: (ms: string) => string; done: string; error: string };
        exit: (phase: string, event: string, target: string) => string;
        live: (phase: string) => string;
        graph: (scene: string) => string;
        zoom: string;
        zoomIn: string;
        zoomOut: string;
        zoomFit: string;
        zoomLevel: (percent: number) => string;
        inspect: {
          hint: string;
          title: (phase: string) => string;
          initial: string;
          final: string;
          entry: string;
          exit: string;
          invokes: string;
          outgoing: string;
          incoming: string;
          via: (trigger: string) => string;
          to: string;
          leaves: (trigger: string, target: string) => string;
          nothing: string;
          close: string;
        };
      };
    };
    /** The icon rail on the right and the panels it opens. */
    studioPanels: {
      rail: string;
      close: string;
      names: Record<"run" | "player" | "conversation" | "sessions", string>;
      sessionsEmpty: string;
      openSession: string;
    };
    /** Loom's refs: the product's refs in the header, and one ref's name and stability. */
    studioRefs: {
      ref: string;
      option: (refNum: number, name: string | null, stable: boolean) => string;
      stable: string;
      stableHint: string;
      settings: string;
      settingsTitle: (productCode: string, refNum: number) => string;
      displayName: string;
      displayNameHint: string;
    };
    /** The storyboard: every scene as a frame, the Scenes section's first view. */
    studioBoard: {
      title: string;
      count: (n: number) => string;
      play: string;
      assemble: string;
      editMedia: string;
      back: string;
      previous: string;
      next: string;
      previousScene: (scene: string) => string;
      nextScene: (scene: string) => string;
      open: string;
      scene: (n: number, id: string) => string;
      shared: string;
      working: string;
      proposed: string;
      unbound: (n: number) => string;
      assets: (n: number) => string;
      noAssets: string;
      empty: string;
    };
    /** The Build stage: what stands between the draft and an assembled module. */
    studioBuild: {
      title: string;
      checking: string;
      unreadable: (reason: string) => string;
      script: Record<"ok" | "warn", string>;
      spec: Record<"ok" | "fail", string>;
      plan: Record<"current" | "missing" | "stale", string>;
      speech: (language: string, bound: number, total: number) => string;
      coverage: (language: string, covered: number, total: number) => string;
      media: (bound: number, total: number) => string;
      canonical: Record<"ok" | "fail", string>;
      checkout: Record<"ok" | "fail", string>;
      unsaved: Record<"ok" | "fail", string>;
      proposal: Record<"ok" | "warn", string>;
      level: Record<"ok" | "warn" | "fail", string>;
      lastRun: (status: string, when: string) => string;
      olderDraft: string;
      openSession: string;
      noRun: string;
    };
    /** Running the stages: Loom's stage picker and Run, and the panel that follows a run. */
    studioRun: {
      stage: string;
      all: string;
      steps: Record<"spec" | "media" | "translations" | "speech" | "images" | "module", string>;
      narration: string;
      status: Record<
        "pending" | "running" | "succeeded" | "skipped" | "failed" | "cancelled",
        string
      >;
      run: string;
      stop: string;
      idle: string;
      progress: (done: number, total: number) => string;
      notes: Record<
        "planCurrent" | "allTranslated" | "needsPenguinAgent" | "noNarration" | "noImages",
        string
      >;
      running: (step: string) => string;
      finished: string;
      stopped: string;
      failed: (reason: string) => string;
      saveFirst: string;
      otherRun: string;
      noAgent: string;
      with: (agent: string) => string;
      live: string;
      waitingForSession: string;
      openInChat: string;
      noRun: string;
    };
    /** The Activity Script editor: scenes that fold, media tags, and a diff against a base. */
    studioScript: {
      label: string;
      scenes: string;
      scenesHelp: string;
      diff: string;
      diffOff: string;
      diffSaved: string;
      diffProposal: string;
      stats: (added: number, removed: number) => string;
      noChanges: string;
      changedScenes: string;
      scene: (n: number) => string;
      proposed: string;
      proposalShown: string;
      acceptProposal: string;
      save: string;
      minimap: string;
      jump: (line: number) => string;
      revert: string;
      autosave: Record<"pending" | "saving" | "saved" | "failed" | "held", string>;
      /** CodeMirror's built-in labels, keyed by its English phrase. */
      editorPhrases: Record<string, string>;
    };
    /** An agent's proposed changes, reviewed in the conversation panel. */
    studioProposal: {
      title: string;
      script: string;
      spec: string;
      media: (key: string, field: "description" | "script", language: string) => string;
      missingAsset: (key: string) => string;
      nothingToApply: string;
      accept: string;
      accepted: string;
      showChange: string;
      saveFirst: string;
      unreadable: (reason: string) => string;
      applyAll: (n: number) => string;
      discard: string;
      discardConfirm: string;
    };
    /** The conversation panel: an agent asked about what the author has open. */
    studioConversation: {
      about: (focus: string) => string;
      wholeActivity: string;
      asset: (key: string, scene: string | null) => string;
      scene: (scene: string) => string;
      placeholder: string;
      send: string;
      stop: string;
      fresh: string;
      openInChat: string;
      threads: string;
      thread: (about: string, when: string) => string;
      empty: string;
      readOnly: string;
      noAgent: string;
      movedTo: (focus: string) => string;
    };
    railCollapse: string;
    railExpand: string;
    railWidth: string;
    sectionNames: Record<
      | "description"
      | "specification"
      | "features"
      | "configuration"
      | "assessment"
      | "scenes"
      | "stats"
      | "speech"
      | "library"
      | "module"
      | "history",
      string
    >;
    /** Loom's Implementation Features: patterns the module assembly reproduces exactly. */
    implementationFeatures: {
      help: string;
      selected: (n: number, total: number) => string;
      source: (module: string) => string;
      unreadable: (reason: string) => string;
    };
    /** Loom's Activity Stats: the media plan counted and weighed. */
    activityStats: {
      reload: string;
      unreadable: (reason: string) => string;
      empty: string;
      type: string;
      language: string;
      count: string;
      bound: string;
      size: string;
      total: string;
      missing: (n: number) => string;
    };
    /** Loom's Configuration Data and Assessment Data: the module's own documents, read-only. */
    moduleDocuments: {
      loading: string;
      unreadable: (reason: string) => string;
      none: string;
      missing: Record<"configuration" | "assessment", string>;
      fromRun: (file: string) => string;
      fromCheckout: (file: string) => string;
      items: (n: number) => string;
      readOnly: string;
    };
    librarySectionEmpty: string;
    sceneAssetTree: string;
    chooseSceneAsset: string;
    unassignedScene: string;
    unassignedSceneHint: string;
    sceneOccurrences: (count: number) => string;
    sceneBoundCount: (bound: number, total: number) => string;
    sharedAsset: string;
    sharedAssetScenes: (scenes: string) => string;
    generatedBinding: string;
    reuseTitle: string;
    reuseHint: string;
    reuseChoose: string;
    reuseApply: string;
    clearBinding: string;
    mediaPathProblems: Record<"empty" | "prefix" | "characters" | "segment" | "length", string>;
    noInAppPreview: string;
    uploadTitle: string;
    uploadHint: Record<"image" | "audio" | "video", string>;
    uploadFile: string;
    uploading: string;
    uploaded: string;
    uploadWrongKind: (kind: string) => string;
    libraryTitle: string;
    libraryHint: string;
    libraryOpen: string;
    librarySearch: string;
    libraryEmpty: string;
    libraryNoMatches: string;
    libraryLoading: string;
    librarySelected: string;
    libraryChoosePrompt: string;
    libraryUse: string;
    libraryFile: string;
    librarySize: string;
    libraryUploadedAt: string;
    uploadedBinding: string;
    checkoutBinding: string;
    playMedia: string;
    waveform: string;
    showWaveform: string;
    waveformLoading: string;
    waveformTrim: {
      hint: string;
      selected: (start: string, end: string) => string;
      play: string;
      remove: string;
      clear: string;
      working: string;
      failed: (reason: string) => string;
      noAudio: string;
      fetchFailed: (status: number) => string;
      remains: (length: string) => string;
      playRemaining: string;
      marked: (at: string) => string;
      keys: string;
    };
    waveformUnavailable: string;
    bulkSpeechTitle: string;
    bulkSpeechHelp: string;
    bulkSpeechTally: (ready: number, total: number) => string;
    bulkSpeechPending: (count: number) => string;
    bulkSpeechBlocked: (count: number) => string;
    bulkSpeechNone: string;
    bulkSpeechGenerate: (count: number) => string;
    bulkSpeechConfirm: (count: number, language: string) => string;
    bulkSpeechStarted: (count: number) => string;
    bulkSpeechQueued: (count: number) => string;
    bulkSpeechStop: string;
    bulkSpeechRetry: string;
    bulkSpeechFilters: string;
    bulkSpeechFilter: Record<
      "all" | "needs" | "translate" | "ready" | "failed" | "blocked",
      string
    >;
    /** One narration across the activity's languages, as Loom's audio panel lists it. */
    narrationLanguages: {
      title: string;
      absent: string;
      spoken: string;
      unspoken: string;
      open: string;
    };
    speechTranslation: Record<"missing" | "outdated" | "translating", string> & {
      translate: string;
      translateAll: (n: number) => string;
      translateAndSpeak: string;
      translateAndSpeakAll: (n: number) => string;
      addLanguage: string;
      add: string;
    };
    bulkSpeechLanguages: string;
    bulkSpeechLanguage: (language: string, ready: number, total: number) => string;
    speechState: Record<
      "ready" | "generating" | "failed" | "missing" | "scriptMissing" | "scriptTooLong",
      string
    >;
    diffShow: string;
    diffHide: string;
    diffTitle: string;
    diffHelp: string;
    diffNone: string;
    diffStats: (added: number, removed: number, regions: number) => string;
    diffPosition: (current: number, total: number) => string;
    diffPrevious: string;
    diffNext: string;
    diffInline: string;
    diffSideBySide: string;
    diffToInline: string;
    diffToSideBySide: string;
    diffRevert: string;
    diffRevertConfirm: string;
    diffScenes: string;
    diffSceneChange: Record<"added" | "removed" | "changed", string>;
    diffFolded: (lines: number) => string;
    diffSavedSide: string;
    diffEditedSide: string;
    diffTooLarge: string;
    mediaCategories: Record<"audio" | "image" | "video" | "animation", string>;
    speechScript: string;
    speechScriptHint: string;
    acceptedAudio: string;
    speechVoice: string;
    regenerateSpeech: string;
    generateSpeech: string;
    speechCandidates: string;
    speechCandidate: string;
    acceptSpeech: string;
    assetLibrary: {
      kind: string;
      binding: string;
      bindings: Record<"any" | "unbound" | "bound", string>;
      search: string;
      planned: string;
      uploaded: string;
      count: (shown: number, total: number) => string;
      columns: Record<"asset" | "type" | "binding" | "scenes" | "file" | "size" | "usedBy", string>;
      sources: Record<"generated" | "upload" | "checkout", string>;
      unbound: string;
      unused: string;
      noPlan: string;
      noMatch: string;
    };
    runSettled: {
      succeeded: (what: string) => string;
      failed: (what: string) => string;
      cancelled: (what: string) => string;
      conflict: (what: string) => string;
    };
    mediaComparison: {
      title: string;
      current: string;
      next: string;
      use: string;
      keep: string;
      noPreview: (path: string) => string;
    };
    olderSpeech: string;
    imageDescription: string;
    imageDescriptionHint: string;
    acceptedImage: string;
    imageHelp: string;
    textHelp: string;
    improveImagePrompt: string;
    improveNarration: string;
    textCandidates: string;
    reviewText: string;
    originalText: string;
    suggestedText: string;
    noOriginalText: string;
    acceptText: string;
    olderText: string;
    matchingText: string;
    mediaTextChanged: string;
    invalidTextCandidate: string;
    textRun: string;
    generateImage: string;
    regenerateImage: string;
    imageCandidates: string;
    acceptImage: string;
    olderImage: string;
    noScenes: string;
    sceneReview: string;
    advancedSpec: string;
    advancedMedia: string;
    audioRun: string;
    imageRun: string;
    speechReady: string;
    speechHelp: string;
    invalidMediaEditor: string;
    mediaTypes: Record<"all" | "audio" | "image" | "video" | "animation", string>;
    speechStatus: Record<
      "running" | "succeeded" | "failed" | "conflict" | "cancelled" | "interrupted",
      string
    >;
    mediaTitle: string;
    previewImage: string;
    loadingImage: string;
    fullImage: string;
    reloadImage: string;
    imageDimensions: (dimensions: string) => string;
    imageUnbound: string;
    imageSaveFirst: string;
    imageUnavailable: string;
    mediaHelp: string;
    planMedia: string;
    rebuildMedia: string;
    mediaManifest: string;
    mediaPathHint: string;
    saveMedia: string;
    mediaCounts: (total: number, bound: number) => string;
    wafRoot: string;
    wafRootHint: string;
    readingMode: string;
    readingModeHint: string;
    readingModeHelp: string;
    chooseReadingMode: string;
    readAlong: string;
    decodable: string;
    assemble: string;
    moduleRun: string;
    moduleReady: string;
    specRun: string;
    assistRun: string;
    previewModule: string;
    olderModule: string;
    previewTitle: string;
    previewHelp: string;
    sandboxTitle: string;
    sandboxHelp: string;
    sandboxBuild: string;
    sandboxBuilding: string;
    sandboxRefresh: string;
    sandboxLog: string;
    sandboxPlay: string;
    sandboxPlayHelp: string;
    sandboxPlayer: string;
    sandboxStop: string;
    sandboxOpen: string;
    previewScene: string;
    previewSceneDefault: string;
    previewLanguageDefault: string;
    previewReload: string;
    previewResolution: (dimensions: string) => string;
    previewResolutionLabel: string;
    previewResolutionOwn: (dimensions: string) => string;
    newActivity: string;
    importFromLoom: string;
    importHelp: string;
    importLoading: string;
    importNoCheckout: string;
    importEmpty: string;
    importSearch: string;
    importAction: string;
    importing: string;
    importRefs: (count: number) => string;
    importProblems: (count: number) => string;
    importImported: string;
    search: string;
    noMatches: string;
    backToActivities: string;
    title: string;
    create: string;
    productCode: string;
    refNum: string;
    name: string;
    type: string;
    standard: string;
    book: string;
    empty: string;
    noProject: string;
    unavailable: string;
    description: string;
    saveDescription: string;
    spec: string;
    saveSpec: string;
    generate: string;
    agent: string;
    penguinAgents: string;
    codingAgents: string;
    codingAgentMedia: string;
    runs: string;
    noRuns: string;
    openSession: string;
    cancel: string;
    candidate: string;
    useCandidate: string;
    reload: string;
    loading: string;
    busy: string;
    saved: string;
    unsaved: string;
    discard: string;
    remoteChanged: string;
    saveFirst: string;
    readOnly: string;
    runningHelp: string;
    collection: string;
    refresh: string;
    status: {
      running: string;
      succeeded: string;
      failed: string;
      conflict: string;
      cancelled: string;
      interrupted: string;
    };
    draftStatus: { draft: string; valid: string; invalid: string };
  };
  codingAgents: {
    agentsTitle: string;
    addAgent: string;
    removeConfirmTitle: string;
    removeConfirmBody: (name: string) => string;
    idLabel: string;
    idHint: string;
    titleLabel: string;
    commandLabel: string;
    commandHint: string;
    argsLabel: string;
    argsHint: string;
    envLabel: string;
    envHint: string;
    setupRequired: string;
    save: string;
    cancel: string;
    busy: string;
    idle: string;
    loadFailed: string;
  };
  nav: {
    activities: string;
    chat: string;
    newChat: string;
    agents: string;
    models: string;
    machines: string;
    plugins: string;
    usage: string;
    traces: string;
    benchmark: string;
    "coding-agents": string;
    lastConversation: string;
    userSettings: string;
    collapseSidebar: string;
    expandSidebar: string;
    collapseGroup: string;
    expandGroup: string;
    pinGroup: string;
    unpinGroup: string;
    org: {
      overview: string;
      chart: string;
      calendar: string;
      tickets: string;
      finance: string;
      handbook: string;
    };
  };
  quickSwitcher: {
    title: string;
    placeholder: string;
    recentsSection: string;
    pagesSection: string;
    loading: string;
    noMatches: string;
    navigateHint: string;
    openHint: string;
    closeHint: string;
  };
  machines: {
    pageTitle: string;
    pageDesc: string;
    imageVersion: (version: string) => string;
    noImage: string;
    empty: string;
    pick: string;
    search: string;
    noMatch: string;
    more: (count: number) => string;
    installedTitle: (count: number) => string;
    installedAt: (version: string, when: string) => string;
    install: string;
    installing: string;
    reinstall: string;
    installed: (version: string) => string;
    alreadyInstalled: (version: string) => string;
    failedAt: (step: string) => string;
    output: string;
    adminOnly: string;
  };
  terminal: {
    title: string;
    newShell: string;
    killShell: string;
    createFailed: string;
    noTerminalApi: string;
    detach: string;
    status: { connecting: string; ready: string; exited: string; error: string };
    exitedWithCode: (code: string) => string;
  };
  dock: {
    addTab: string;
    closeTab: string;
    hideDock: string;
    moveToRight: string;
    moveToBottom: string;
    resize: string;
    rightDock: string;
    bottomDock: string;
    draftEmpty: string;
    killConfirmTitle: string;
    killConfirmBody: (name: string) => string;
    launcher: string;
    launcherCaption: string;
    launcherOpen: string;
    launcherClose: string;
    launcherPending: string;
    launcherPanels: string;
    launcherHide: string;
    launcherHiddenToast: string;
  };
  tracePanel: { empty: string; emptyHint: string; loadFailed: string };
  settings: {
    language: string;
    languageInfo: string;
    systemSettings: string;
    groupPersonal: string;
    groupServer: string;
    profile: string;
    generalTitle: string;
    appearanceTitle: string;
    accountTitle: string;
    importTrace: string;
    importTraceInfo: string;
    importTraceProject: string;
    importTraceAgent: string;
    importTracePick: string;
    importTraceRunning: string;
    importTraceDone: (target: string) => string;
    importTraceTooLarge: string;
    proxyTitle: string;
    proxyInfo: string;
    proxyForApp: string;
    proxyForAgent: string;
    proxyAddress: string;
    proxyAddressPlaceholder: string;
    proxyProbe: string;
    proxyProbeRun: string;
    proxyProbeRunning: string;
    proxyProbeLatency: (ms: number) => string;
    proxyProbeReachableState: string;
    proxyProbeIdle: string;
    proxyProbeFailure: {
      timeout: string;
      dns: string;
      refused: string;
      tls: string;
      network: string;
    };
    uploadLimitsTitle: string;
    attachmentMaxMb: string;
    attachmentTotalMb: string;
    attachmentMaxMbHint: (min: number, max: number) => string;
    attachmentTotalMbHint: (min: number, max: number) => string;
    uploadLimitsInfo: (count: number, imageMb: number) => string;
    theme: string;
    themeInfo: string;
    themeLight: string;
    themeDark: string;
    followSystem: string;
    terminalTheme: string;
    terminalThemeInfo: string;
    followAppTheme: string;
    langEn: string;
    fontSize: string;
    fontSizeInfo: string;
    fontSmall: string;
    fontMedium: string;
    fontLarge: string;
    accent: string;
    accentInfo: string;
    launcher: string;
    launcherInfo: string;
    toolAliases: string;
    toolAliasesInfo: string;
    notifications: string;
    notificationsInfo: string;
    notificationsDenied: string;
    notificationsDismissed: string;
    notificationsUnsupported: string;
    trayIcon: string;
    trayIconInfo: string;
    currencyInfo: string;
    changePasswordInfo: string;
    companyModeTitle: string;
    companyModePersonal: string;
    companyModePersonalInfo: string;
    companyModeServer: string;
    companyModeServerInfo: string;
    accentNames: Record<string, string>;
  };
  update: {
    lastUpdated: (date: string) => string;
    newVersionBadge: string;
    badgeDownloading: string;
    badgeReady: string;
    newVersion: (v: string) => string;
    restartToUpdate: (v: string | null) => string;
    updatesAvailable: string;
    checkNow: string;
    checking: string;
    rowDownloading: (v: string | null, percent: number | null) => string;
    rowRestarting: string;
    rowUnsupported: string;
    title: string;
    currentVersion: (v: string) => string;
    checkingBody: string;
    upToDate: string;
    checkFailed: string;
    checkDisabled: string;
    releaseNotes: string;
    openReleases: string;
    availableBodyRelease: string;
    availableBodyClient: string;
    adminOnly: string;
    downloadAndInstall: string;
    later: string;
    background: string;
    downloading: (v: string | null) => string;
    downloadProgress: string;
    phaseResolving: string;
    phaseDownloading: string;
    phaseInstalling: string;
    ready: (v: string | null) => string;
    readyBodyRelease: string;
    readyBodyClient: string;
    readyBodyManual: string;
    restartNow: string;
    restarting: string;
    restartingBodyRelease: string;
    restartingBodyClient: string;
    failed: string;
    retry: string;
    unsupportedDev: string;
    unsupportedNonAppImage: string;
    unsupportedNotViaCli: string;
    unsupportedCli: string;
    foundNew: (v: string) => string;
    foundNewUnnamed: string;
    readyToast: (v: string | null) => string;
    failedToast: string;
    unsupportedToast: string;
    clientUpdateFailed: (detail: string) => string;
    requestFailed: (detail: string) => string;
    restartTimedOut: string;
  };
  todo: {
    pluginUpdates: (n: number) => string;
    presetUpdates: (n: number) => string;
    unexpectedErrors: (n: number) => string;
    pending: string;
    dismiss: string;
    markRead: string;
    changesWithAdded: (added: number, updated: number) => string;
    changesUpgradable: (updated: number) => string;
    updateNow: string;
    willTouch: string;
    agentsConfirmTitle: (n: number) => string;
    pluginsConfirmTitle: (n: number) => string;
    pluginsConfirmBody: string;
    modelsConfirmTitle: (n: number) => string;
    bulkDone: (ok: number) => string;
    bulkPartial: (ok: number, failed: string) => string;
    listSeparator: string;
  };
  notify: { taskCompleteTitle: string; taskCompleteBody: (session: string) => string };
  common: {
    save: string;
    cancel: string;
    close: string;
    create: string;
    delete: string;
    edit: string;
    settings: string;
    confirm: string;
    gotIt: string;
    loading: string;
    saved: string;
    saving: string;
    noChangesToSave: string;
    confirmSaveTitle: string;
    confirmSaveBody: string;
    none: string;
    retry: string;
    unknownError: string;
    requiredField: string;
    copy: string;
    copied: string;
    moreInfo: string;
    moreInfoAbout: (subject: string) => string;
    name: string;
    username: string;
    role: string;
    actions: string;
    created: string;
    cost: string;
    time: string;
  };
  semanticId: {
    generateIdLabel: string;
    generateId: string;
    idGenerateHint: string;
    idSuggest: {
      fromName: string;
      placeholder: (reason: string) => string;
      reasons: {
        no_default_model: string;
        model_failed: string;
        unusable_answer: string;
        no_ascii: string;
      };
      reasonUnknown: string;
    };
  };
  auth: {
    usernameHint: string;
    password: string;
    passwordHint: string;
    showPassword: string;
    hidePassword: string;
    login: string;
    logout: string;
    logoutConfirmTitle: string;
    logoutConfirmBody: string;
    admin: string;
    defaultAdminNote: string;
    forgotAdminNote: string;
    claimFailedTitle: string;
    claimFailedDesktop: string;
    claimFailedServer: string;
  };
  profile: {
    avatar: string;
    avatarInfo: string;
    changeAvatar: string;
    restoreDefault: string;
    restoreDefaultOf: (subject: string) => string;
    avatarTooLarge: string;
    avatarUnreadable: string;
    displayName: string;
    displayNameHint: string;
    displayNamePlaceholder: string;
  };
  account: {
    changePassword: string;
    oldPassword: string;
    oldPasswordHint: string;
    newPassword: string;
    confirmPassword: string;
    passwordMismatch: string;
    initialPasswordBanner: string;
    changeNow: string;
  };
  admin: {
    users: string;
    roleAdmin: string;
    roleUser: string;
    createUser: string;
    initialPassword: string;
    initialPasswordFlag: string;
    defaultProjectNote: (id: string) => string;
    resetPassword: string;
    resetPasswordTitle: (u: string) => string;
    resetPasswordNote: string;
    deleteUserTitle: (u: string) => string;
    deleteUserConfirm: (u: string) => string;
  };
  project: {
    selectProject: string;
    switcher: string;
    create: string;
    createTitle: string;
    id: string;
    idHint: string;
    idPrefixHint: string;
    displayName: string;
    displayNameHint: string;
    settings: string;
    settingsTitle: string;
    members: string;
    addMember: string;
    removeMember: string;
    chatDefaultsTitle: string;
    chatDefaultsHint: string;
    chatDefaultsAgent: string;
    chatDefaultsNotSet: string;
    chatDefaultsApprovalNotSet: string;
    chatDefaultsThinkingNotSet: string;
    chatDefaultsModelHint: string;
    settingsTabGeneral: string;
    settingsTabMembers: string;
    settingsTabDefaults: string;
    settingsTabSecurity: string;
    projectIdLabel: string;
    deleteProjectDesc: string;
    commandPolicyInfo: string;
    commandPolicyEnable: string;
    commandPolicyEnableDesc: string;
    commandPolicyRules: string;
    commandPolicyRestore: string;
    commandPolicyAddRule: string;
    commandPolicyEditRule: string;
    commandPolicyApplyRule: string;
    commandPolicyEmpty: string;
    commandPolicyOn: string;
    commandPolicyOff: string;
    commandPolicyRuleName: string;
    commandPolicyRulePattern: string;
    commandPolicyRuleDesc: string;
    commandPolicyInvalidPattern: string;
    deleteProject: string;
    deleteConfirm: string;
    deleteDefaultForbidden: string;
    deleteLastForbidden: string;
    noCredentialTitle: string;
    noCredentialBody: string;
    goToModels: string;
    later: string;
  };
  aiCreate: {
    withAi: string;
    manual: string;
    editInChat: string;
    copyPrompt: string;
    examplesTitle: string;
    fullPrompt: string;
    byAgent: (name: string) => string;
    chooseAgent: string;
    placeholder: string;
    promptLabel: string;
    noAgent: string;
  };
  agent: {
    savedTakesEffect: string;
    savedTakesEffectNow: string;
    takesEffectSuffix: string;
    listTitle: string;
    searchPlaceholder: string;
    searchEmpty: string;
    create: string;
    createTitle: string;
    id: string;
    idHint: string;
    idGenerateHint: string;
    nameHint: string;
    description: string;
    createPlugins: string;
    createPluginsPlaceholder: string;
    createPluginsPicked: (n: number) => string;
    createPluginsHint: string;
    createPluginsEmpty: string;
    createSkillsPlaceholder: string;
    createSkillsPicked: (n: number) => string;
    createDirSkills: string;
    createDirSkillsPick: string;
    createDirSkillsHint: string;
    createDirSkillsEmpty: string;
    createDirSkillsFound: (n: number) => string;
    createDirSkillsClear: string;
    createSnapshot: string;
    createSnapshotPick: string;
    createSnapshotHint: string;
    createSnapshotSkillsOff: string;
    createSnapshotClear: string;
    aiCreateTitle: string;
    aiCreateIntro: string;
    aiCreatePlaceholder: string;
    aiExamples: { key: string; label: string; description: string; prompt: string }[];
    aiCreateTail: string;
    firstAgentTitle: string;
    firstAgentDesc: string;
    sessionCount: (n: number) => string;
    toolCount: (n: number) => string;
    vaultKeyCount: (n: number) => string;
    scheduleCount: (n: number) => string;
    memoryCount: (n: number) => string;
    updatedAt: string;
    activity: (days: number) => string;
    settings: string;
    backToList: string;
    tabOverview: string;
    tabPrompt: string;
    tabMemory: string;
    tabRuntime: string;
    tabTools: string;
    tabSkills: string;
    tabHooks: string;
    tabVault: string;
    tabSchedules: string;
    stateDir: string;
    copyStateDir: string;
    agentsMd: string;
    systemPrompt: string;
    placeholdersTitle: string;
    insertPlaceholder: string;
    placeholders: ReadonlyArray<readonly [string, string]>;
    maxTurns: string;
    maxTokens: string;
    thinkingLevel: string;
    thinkingLevelOptions: ReadonlyArray<readonly [string, string]>;
    thinkingLevelNoneKept: string;
    timeoutMs: string;
    timeoutMsHint: string;
    compaction: string;
    maxContextLength: string;
    maxContextLengthHint: string;
    maxSessionTurns: string;
    maxSessionTurnsHint: string;
    compactionMode: string;
    compactionModeOptions: ReadonlyArray<readonly [string, string]>;
    compactionPrompt: string;
    maxTurnsInvalid: string;
    timeoutInvalid: string;
    toolFieldInvalid: (name: string, field: string) => string;
    toolPermission: string;
    permissionReadLabel: string;
    permissionReadDescription: string;
    permissionReadWriteLabel: string;
    permissionReadWriteDescription: string;
    toolTimeout: string;
    toolMaxOutput: string;
    toolCallDescription: string;
    callDescriptionHint: string;
    mcpServers: string;
    mcpDesc: string;
    mcpEmpty: string;
    mcpAdd: string;
    mcpEditTitle: string;
    mcpRemove: string;
    mcpName: string;
    mcpNameHint: string;
    mcpTransport: string;
    mcpTransportStdio: string;
    mcpTransportHttp: string;
    mcpTransportSse: string;
    mcpTarget: string;
    mcpCommand: string;
    mcpArgs: string;
    mcpArgsHint: string;
    mcpEnv: string;
    mcpEnvHint: string;
    mcpCwd: string;
    mcpCwdHint: string;
    mcpUrl: string;
    mcpHeaders: string;
    mcpHeadersHint: string;
    mcpPermission: string;
    mcpPermissionAuto: string;
    mcpPermissionAutoLabel: string;
    mcpPermissionAutoDescription: string;
    mcpPermissionReadDescription: string;
    mcpPermissionReadWriteDescription: string;
    mcpPermissionHint: string;
    mcpConnectTimeout: string;
    mcpBudgetsHint: string;
    mcpNameInvalid: string;
    mcpUrlInvalid: string;
    mcpLineInvalid: (line: number) => string;
    mcpNumberInvalid: string;
    mcpDuplicateName: string;
    mcpTest: string;
    mcpTesting: string;
    mcpTestOk: (toolCount: number, latencyMs?: number) => string;
    mcpTestFail: (detail: string) => string;
    mcpTestAllConfirm: (n: number) => string;
    mcpTestAllStart: string;
    mcpTestPending: string;
    mcpTestBadge: (toolCount: number, latencyMs?: number) => string;
    mcpTestBadgeFail: string;
    mcpDeleteTitle: string;
    mcpDeleteConfirm: (name: string) => string;
    defaultValue: string;
    deleteAgent: string;
    builtinUndeletable: string;
    deleteConfirm: (name: string) => string;
    stateTitle: string;
    stateVersion: string;
    transferDesc: string;
    exportSnapshot: string;
    importSnapshot: string;
    importing: string;
    importDone: (v: number) => string;
    importConflictTitle: string;
    importConflictBody: string;
    resetConfigTitle: string;
    resetConfigAction: string;
    resetConfigConfirmBody: string;
    resetConfigDone: string;
    kernelTitle: string;
    kernelLegacy: string;
    kernelOutdatedHint: string;
    kernelUpdateNeeded: string;
    kernelUpToDate: string;
    kernelUpdateTitle: string;
    kernelCurrent: string;
    kernelLatest: string;
    kernelUpdateAction: string;
    kernelUpdateConfirmBody: string;
    kernelUpdateDone: (version: string, advanced: number) => string;
    kernelUpdateKeptIntro: string;
    kernelListSeparator: string;
  };
  models: {
    title: string;
    addCustom: string;
    addToGroup: string;
    editTitle: string;
    addTitle: string;
    addTitleVendor: string;
    addProtocolHint: string;
    vendorProtocolHint: (vendor: string) => string;
    addProtocolHintPinned: (protocol: string) => string;
    addProtocolHintPinnedGateway: (protocol: string) => string;
    autoRouteNone: string;
    useCustomGroup: string;
    addGroup: string;
    addGroupTitle: string;
    addGroupDesc: string;
    groupModeCreate: string;
    groupModeImport: string;
    groupImportAll: string;
    groupImportNeedUrl: string;
    groupImportKeyHint: string;
    groupImportListing: string;
    groupImportSaving: (n: number) => string;
    groupImportUnsupported: string;
    groupImportFailed: string;
    groupImportEmpty: string;
    groupImported: (added: number, skipped: number) => string;
    groupNameLabel: string;
    groupNameHint: string;
    groupNameInvalid: string;
    groupNameExists: string;
    groupEmptyHint: string;
    deleteGroup: string;
    deleteGroupTitle: string;
    deleteGroupConfirm: (label: string, n: number) => string;
    groupDeleted: (n: number) => string;
    searchPlaceholder: string;
    noSearchResults: string;
    syncCatalog: string;
    syncCatalogHint: string;
    syncDone: (added: number, updated: number) => string;
    syncUpToDate: string;
    aiAddTitle: string;
    aiAddIntro: string;
    aiAddPlaceholder: string;
    aiAddExamples: { key: string; label: string; description: string; prompt: string }[];
    aiAddTail: (projectId: string) => string;
    platformSync: string;
    homepage: string;
    speedTest: string;
    speedTestTitle: string;
    speedTestConfirm: (n: number) => string;
    speedTestStart: string;
    speedPending: string;
    speedFailed: string;
    ttftTitle: string;
    tpsTitle: string;
    modelCount: (n: number) => string;
    modelId: string;
    modelIdHint: string;
    displayName: string;
    displayNameHint: string;
    providerGroup: string;
    contextWindow: string;
    tokenUnit: string;
    contextWindowHint: string;
    maxTokens: string;
    maxTokensHint: string;
    maxTokensTitle: string;
    maxTokensInvalid: string;
    clientTypeLocked: (t: string) => string;
    protocol: string;
    protocolNames: Record<string, string | undefined>;
    protocolTriggerTitle: (name: string) => string;
    protocolUnset: string;
    detectProtocol: string;
    detectProtocolHint: string;
    detecting: string;
    detectedProtocol: (name: string) => string;
    detectedProtocolAndUrl: (protocol: string, url: string) => string;
    detectFailedBody: string;
    detectFellBack: string;
    addProtocolHintDetect: string;
    addTitleCustom: string;
    vision: string;
    detectVision: string;
    detectingVision: string;
    detectVisionHint: string;
    detectVisionNeedsId: string;
    detectVisionOk: string;
    detectVisionNo: string;
    visionOffProxyHint: string;
    fastMode: string;
    fastModeHint: string;
    fastModeUnsupported: string;
    fastModeConfirmTitle: string;
    fastModeConfirmBody: string;
    fastModeConfirmPreview: string;
    fastModeBadge: string;
    visionBadge: string;
    freeBadge: string;
    recommendedGroup: string;
    discountBadge: (pct: number) => string;
    discountTitle: (pct: number) => string;
    offPeakTitle: (pct: number, peak: PeakWindows) => string;
    visionModelBadge: string;
    usedTokens: (v: string) => string;
    usedTokensTitle: string;
    setVisionModel: string;
    visionModelHint: string;
    priceUnitShort: string;
    testConnection: string;
    testing: string;
    testOk: (ms: number) => string;
    testFailed: (msg: string) => string;
    priceCacheRead: string;
    priceCacheWrite: string;
    priceOutput: string;
    promotionPriceHint: (pct: number) => string;
    currency: string;
    currencyUsd: string;
    currencyCny: string;
    apiKey: string;
    apiKeyKeepHint: string;
    apiKeyEnvHint: (envKey: string) => string;
    keyConfigured: string;
    clearApiKey: string;
    baseUrl: string;
    baseUrlHint: string;
    baseUrlSuffixTitle: string;
    baseUrlRequired: string;
    contextWindowDefaultHint: (n: number) => string;
    confirmDeleteTitle: string;
    confirmDelete: (name: string) => string;
    groupApiKey: string;
    groupApiKeyTitle: (label: string) => string;
    groupApiKeyHint: (n: number) => string;
    getApiKey: string;
    getModelIds: string;
    groupKeyApplied: (n: number) => string;
    oauthKey: string;
    viewLocalCli: string;
    viewApiProviders: string;
    localCliIntro: string;
    installedClis: (n: number) => string;
    availableClis: (n: number) => string;
    cliRescan: string;
    cliScanning: string;
    cliAddAgent: string;
    cliModel: string;
    cliEffort: string;
    cliSynced: string;
    cliDefault: string;
    cliModelsUnknown: string;
    cliSignedIn: string;
    cliSignInRequired: string;
    cliStartChat: string;
    cliRemove: string;
    cliInstall: string;
    cliNone: string;
    cliScanFailed: string;
    cliModelSummary: (name: string) => string;
    cliTest: string;
    cliTesting: string;
    cliRetest: string;
    cliTestOk: (name: string, ms: number, reply: string) => string;
    cliTestStart: (name: string, message: string) => string;
    cliTestTimeout: (name: string) => string;
    cliTestFailed: (name: string, message: string) => string;
    cliTestReply: (name: string, reply: string) => string;
    accessAll: string;
    accessApiKey: string;
    accessSubscription: string;
    noAccessResults: string;
    copilotConnect: string;
    chatgptConnect: string;
    chatgptDisconnect: string;
    chatgptDisconnected: string;
    chatgptDisconnectBody: string;
    chatgptIntro: string;
    chatgptCode: string;
    chatgptApplyFailed: string;
    chatgptApplied: (count: number) => string;
    copilotDisconnect: string;
    copilotDisconnectBody: string;
    copilotDisconnected: string;
    copilotIntro: string;
    copilotCode: string;
    copilotApplyFailed: string;
    copilotTimedOut: string;
    copilotApplied: (count: number) => string;
    oauthTitle: (label: string) => string;
    oauthIntro: (label: string, n: number) => string;
    oauthAuthorize: string;
    oauthWaiting: string;
    oauthAppliedBody: (provider: string, n: number) => string;
    oauthManualSwitch: string;
    oauthCallbackSwitch: string;
    oauthManualHint: string;
    oauthCodeLabel: string;
    oauthSubmitCode: string;
    oauthTimedOut: string;
    oauthRetry: string;
    oauthErrors: {
      invalid_request: string;
      code_rejected: string;
      upstream_failed: string;
      unreachable: string;
      apply_failed: string;
    };
    platformKeyIntro: (n: number) => string;
    platformKeyAppliedBody: (n: number) => string;
    platformKeyStarting: string;
    platformKeyApplying: string;
    platformKeyErrors: {
      unreachable: string;
      upstream_failed: string;
      invalid_key: string;
      expired: string;
      locked: string;
      already_delivered: string;
      apply_failed: string;
    };
    providerEnvNotes: Record<string, string | undefined>;
    confirmVisionModelTitle: string;
    confirmVisionModel: (name: string) => string;
    confirmSaveTitle: string;
    confirmSave: (name: string) => string;
    confirmDefaultTitle: string;
    confirmDefault: (name: string) => string;
    default: string;
    setDefault: string;
    remove: string;
    readOnlyHint: string;
    empty: string;
    noKey: string;
    readFromEnv: string;
    showModelsWithoutKey: (n: number) => string;
    modelIdExists: string;
    pricingAllOrNone: string;
    pricingInvalid: string;
    contextWindowInvalid: string;
  };
  memory: {
    desc: string;
    enable: string;
    userScope: string;
    templateMissing: string;
    insertPlaceholder: string;
    insertPlaceholderDone: string;
    promptSection: string;
    promptSectionHint: string;
    promptLabel: string;
    workspacePromptLabel: string;
    promptPlaceholders: string[][];
    insertToken: string;
    itemCount: (n: number) => string;
    emptyScope: string;
    emptyUserScope: string;
    add: string;
    addScopeLabel: (scope: string) => string;
    addTitle: string;
    addWhy: string;
    addContentLabel: string;
    addContentPlaceholder: string;
    addPromptLead: { user: string; workspace: string };
    view: string;
    edit: string;
    editTitle: string;
    editWhy: string;
    editRequirementLabel: string;
    editRequirementPlaceholder: string;
    editPromptLabel: string;
    editCopyPrompt: string;
    editOpenChat: string;
    delete: string;
    deleteTitle: string;
    deleteConfirm: (name: string) => string;
    deleteDone: string;
    editPromptLead: (title: string) => string;
    editPromptTail: string;
    exportScope: string;
    exportScopeHint: string;
    exportScopeLabel: (scope: string) => string;
    importScope: string;
    importScopeHint: string;
    importScopeLabel: (scope: string) => string;
    importTitle: string;
    importWhy: string;
    importFile: (name: string, count: number) => string;
    importModeLabel: string;
    importModeSkip: string;
    importModeSkipHint: string;
    importModeOverwrite: string;
    importModeOverwriteHint: string;
    importModeReplace: string;
    importModeReplaceHint: string;
    importAction: string;
    importInvalidFile: string;
    importEmptyFile: string;
    importConfirmTitle: string;
    importWillOverwrite: (names: string[]) => string;
    importWillRemove: (names: string[]) => string;
    importWillReplaceIndex: string;
    importIrreversible: string;
    importDone: (added: number, overwritten: number, removed: number) => string;
    importNothingNew: string;
  };
  vault: {
    desc: string;
    key: string;
    value: string;
    valueMasked: string;
    add: string;
    addTitle: string;
    remove: string;
    deleteTitle: string;
    deleteConfirm: (key: string) => string;
    overwriteTitle: string;
    overwriteConfirm: (key: string) => string;
    empty: string;
    readOnlyHint: string;
    keyHint: string;
    keyInvalid: string;
    valueRequired: string;
    aiAddTitle: string;
    aiAddIntro: string;
    aiAddPlaceholder: string;
    aiAddExamples: { key: string; label: string; description: string; prompt: string }[];
    aiAddTail: (agentId: string, projectId: string) => string;
    injection: {
      enable: string;
      templateMissing: string;
      legacyTemplate: string;
      insertPlaceholder: string;
      migrate: string;
      promptSection: string;
      promptSectionHint: string;
      promptLabel: string;
      promptPlaceholders: ReadonlyArray<readonly [string, string]>;
    };
  };
  schedule: {
    desc: string;
    readOnlyHint: string;
    colStatus: string;
    colPeriod: string;
    colTarget: string;
    colFireTimes: string;
    colQueued: string;
    statusNames: Record<string, string>;
    queued: string;
    once: string;
    newSession: string;
    invalidFiles: string;
    empty: string;
    enable: string;
    disable: string;
    addTitle: string;
    editTitle: (name: string) => string;
    nameHint: string;
    prompt: string;
    enabled: string;
    startAt: string;
    endAt: string;
    period: string;
    periodPlaceholder: string;
    target: string;
    targetNew: string;
    targetSession: string;
    sessionId: string;
    chooseSession: string;
    sessionSearch: string;
    sessionNoMatch: string;
    sessionEmpty: string;
    workspace: string;
    model: string;
    modelDefault: string;
    deleteTitle: string;
    deleteConfirm: (name: string) => string;
    toastSaved: string;
    toastEnabled: string;
    toastDisabled: string;
    targetThisSession: string;
    panelTitle: string;
    panelSubtitle: string;
    panelSearchPlaceholder: string;
    filterAll: string;
    filterActive: string;
    filterPaused: string;
    filterCompleted: string;
    panelEmpty: string;
    panelNoMatch: string;
    panelDraftEmpty: string;
    rowActions: string;
    human: {
      everyDay: (time: string) => string;
      everyWeek: (weekday: string, time: string) => string;
      everyDays: (n: number, time: string) => string;
      everyHours: (n: number) => string;
      everyMinutes: (n: number) => string;
      once: (when: string) => string;
      next: (when: string) => string;
      today: (time: string) => string;
      tomorrow: (time: string) => string;
      onDate: (monthDay: string, time: string) => string;
      onDateWithYear: (year: number, monthDay: string, time: string) => string;
    };
    aiCreateTitle: string;
    aiCreateInSessionDesc: string;
    aiCreateDesc: string;
    byAgentInSession: (name: string) => string;
    editInSession: string;
    aiCreateInSessionTail: string;
    aiCreateTail: (agentId: string) => string;
    suggestionsTitle: string;
    suggestions: {
      dailyBrief: {
        name: string;
        hint: string;
        description: string;
        prompt: string;
        agentPrompt: string;
      };
      weeklyReview: {
        name: string;
        hint: string;
        description: string;
        prompt: string;
        agentPrompt: string;
      };
      followUp: {
        name: string;
        hint: string;
        description: string;
        prompt: string;
        agentPrompt: string;
      };
      monitor: {
        name: string;
        hint: string;
        description: string;
        prompt: string;
        agentPrompt: string;
      };
    };
    injection: {
      enable: string;
      templateMissing: string;
      insertPlaceholder: string;
      promptSection: string;
      promptSectionHint: string;
      promptLabel: string;
      promptPlaceholders: ReadonlyArray<readonly [string, string]>;
    };
  };
  plugins: {
    installedTitle: string;
    installedDesc: string;
    installedEmpty: string;
    stateActive: string;
    builtin: string;
    builtinHint: string;
    installedRestart: string;
    stateFailed: string;
    replacesLabel: string;
    restartPending: string;
    uninstall: string;
    install: string;
    installing: string;
    deploymentInstalledToast: (name: string) => string;
    deploymentFailedToast: (name: string, reason: string) => string;
    applyConfirmInstall: (name: string) => string;
    applyConfirmRemove: (name: string) => string;
    applyConfirmBody: string;
    pageTitle: string;
    pageDesc: string;
    installedSection: (n: number) => string;
    availableSection: (n: number) => string;
    notInstalled: string;
    filterCategories: string;
    filterKind: string;
    filterState: string;
    filterClear: string;
    kindLabel: { skills: string; hooks: string; modules: string };
    stateLabel: {
      installed: string;
      available: string;
      running: string;
      restart: string;
      failed: string;
    };
    noMatch: string;
    shippedNoEntry: string;
    libraryBuiltinHint: string;
    pluginCount: (n: number) => string;
    searchPlaceholder: string;
    detailSkills: string;
    detailHooks: string;
    usedByAgents: (n: number) => string;
    quickInvokeNeedsInstall: string;
    installedToast: (plugin: string, agent: string) => string;
    uninstalledToast: (plugin: string, agent: string) => string;
    updateOutdated: (n: number) => string;
    updateConfirmTitle: (name: string) => string;
    updateConfirmWarning: (name: string) => string;
    updatedToast: (plugin: string, n: number) => string;
    uninstallConfirmTitle: (name: string) => string;
    uninstallConfirmBody: (plugin: string, agent: string) => string;
  };
  hooks: {
    agentTabDesc: string;
    agentTabEmpty: string;
    readOnlyHint: string;
    hookCount: (n: number) => string;
    exportHook: string;
    importHook: string;
    importChatTitle: string;
    importChatWhy: string;
    importSourceLabel: string;
    importSourceHint: string;
    importSourcePlaceholder: string;
    importSourceToken: string;
    importPromptLabel: string;
    importPromptLead: (s: string) => string;
    importCopyPrompt: string;
    importOpenChat: string;
    importUploadTitle: string;
    importUploadDesc: string;
    importUploadAction: string;
    importUploading: string;
    importDoneToast: string;
    importOverwriteTitle: string;
    importOverwriteBody: (name: string) => string;
    importOverwriteAction: string;
    importPromptTail: (projectId: string, agentId: string) => string;
    uninstallConfirmTitle: (name: string) => string;
    uninstallConfirmBody: (name: string, agent: string) => string;
    uninstalledToast: (name: string, agent: string) => string;
    injection: { enable: string; enableHint: string; savedToast: string };
  };
  pluginRegistry: {
    pageTitle: string;
    empty: string;
    specifierHint: string;
    back: string;
    readme: string;
    noReadme: string;
    notFound: string;
    repository: string;
    homepage: string;
    authors: string;
    license: string;
    copySpecifier: string;
    installHint: string;
  };
  skills: {
    quickInvoke: string;
    quickInvokeText: (name: string) => string;
    selectAll: string;
    selectNone: string;
    selectedCount: (n: number) => string;
    manageInstall: string;
    manageInstallTitle: (name: string) => string;
    install: string;
    installed: string;
    uninstall: string;
    skillCount: (n: number) => string;
    updateAction: string;
    uninstalledToast: (skill: string, agent: string) => string;
    uninstallConfirmTitle: (name: string) => string;
    uninstallConfirmBody: (skill: string, agent: string) => string;
    agentTabDesc: string;
    agentTabEmpty: string;
    exportSkill: string;
    importSkill: string;
    importChatTitle: string;
    importChatWhy: string;
    importSourceLabel: string;
    importSourceHint: string;
    importSourcePlaceholder: string;
    importSourceToken: string;
    importPromptLabel: string;
    importPromptLead: {
      webUrl: (s: string) => string;
      repoUrl: (s: string) => string;
      localPath: (s: string) => string;
      command: (s: string) => string;
      reference: (s: string) => string;
    };
    importPromptTail: string;
    importCopyPrompt: string;
    importOpenChat: string;
    importUploadTitle: string;
    importUploadDesc: string;
    importUploadAction: string;
    importUploading: string;
    importDoneToast: string;
    importOverwriteTitle: string;
    importOverwriteBody: (name: string) => string;
    importOverwriteAction: string;
    injection: {
      enable: string;
      templateMissing: string;
      legacyTemplate: string;
      insertPlaceholder: string;
      migrate: string;
      promptSection: string;
      promptSectionHint: string;
      promptLabel: string;
      promptPlaceholders: ReadonlyArray<readonly [string, string]>;
    };
  };
  chat: {
    thinkingLevelChangeNote: string;
    newSessionMenu: string;
    chooseAgent: string;
    chooseModel: string;
    codingAgentTextOnly: string;
    thinkingLevel: string;
    thinkingLevelNames: Readonly<Record<string, string>>;
    thinkingLevelMenuName: (name: string, level: string) => string;
    thinkingSwitchTitle: string;
    thinkingSwitchBody: (to: string) => string;
    thinkingSwitchBusyHint: string;
    thinkingSwitchCompactFirst: string;
    thinkingSwitchConfirm: string;
    thinkingSwitchCompacting: string;
    thinkingSwitchApplied: (to: string) => string;
    thinkingSwitchCompactFailed: string;
    workspaceUseThis: string;
    workspaceUp: string;
    workspaceNoSubdirs: string;
    workspaceAuto: string;
    workspaceClear: string;
    workspaceDirInvalid: string;
    groupByWorkspace: string;
    groupByAgent: string;
    groupByTime: string;
    timeGroups: { day: string; month: string; earlier: string };
    searchSessions: string;
    searchSessionsPlaceholder: string;
    searchClear: string;
    searchNoMatches: string;
    listSettings: string;
    groupModeSection: string;
    sortModeSection: string;
    sortManual: string;
    sortRecent: string;
    newWorkspaceEntity: string;
    workspaceMenu: string;
    renameWorkspace: string;
    renameWorkspaceLabel: string;
    renameWorkspaceHint: string;
    deleteWorkspace: string;
    deleteWorkspaceConfirm: (name: string) => string;
    tempWorkspaces: string;
    newSessionInWorkspace: string;
    draftSubtitle: string;
    exampleFolders: { webapps: string; agents: string; schedules: string };
    exampleFillHint: string;
    shortcuts: {
      folder: string;
      new: string;
      newFromComposer: string;
      createTitle: string;
      editTitle: string;
      titleLabel: string;
      titleHint: (max: number) => string;
      promptLabel: string;
      promptHint: (max: number) => string;
      promptInfo: string;
      titleTooLong: (max: number) => string;
      promptTooLong: (max: number) => string;
      deleteTitle: string;
      deleteConfirm: (title: string) => string;
    };
    exampleTasks: {
      game: { label: string; desc: string; prompt: string };
      gamecenter: { label: string; desc: string; prompt: string };
      lol: { label: string; desc: string; prompt: string };
      rhythmRunner: { label: string; desc: string; prompt: string };
      investmentCopilot: { label: string; desc: string; prompt: string };
      rag: { label: string; desc: string; prompt: string };
      agentBenchmarkBuild: { label: string; desc: string; prompt: string };
      agentOptimization: { label: string; desc: string; prompt: string };
      dailyPlan: { label: string; desc: string; prompt: string };
      githubDigest: { label: string; desc: string; prompt: string };
      memoryReview: { label: string; desc: string; prompt: string };
    };
    sessionList: string;
    defaultSessionTitle: string;
    agent: string;
    model: string;
    workspace: string;
    workspaceHint: string;
    workspaceHintShort: string;
    approvalMode: string;
    approvalModeNames: Record<string, string>;
    approvalModes: Record<string, string>;
    statusRunning: string;
    statusCompacting: string;
    statusCompletedUnread: string;
    backgroundTasks: (n: number) => string;
    sessionScheduled: string;
    backgroundCall: string;
    sendToBackground: string;
    sendToBackgroundHint: string;
    pendingApprovals: (n: number) => string;
    jumpToLatest: string;
    loadingEarlier: string;
    loadEarlierRetry: string;
    historyBeginning: string;
    outlineTitle: string;
    outlineTickLabel: (n: number, question: string) => string;
    outlineNoText: string;
    outlineAnswering: string;
    inputPlaceholder: string;
    inputPlaceholderShort: string;
    steerPlaceholder: string;
    steerPlaceholderShort: string;
    steerSend: string;
    steerQueuedIndicator: string;
    steerQueuedItem: (content: string) => string;
    userSteering: string;
    steerModeLabel: string;
    steerModeSteer: string;
    steerModeSteerHint: string;
    steerModeFollowUp: string;
    steerModeFollowUpHint: string;
    followUpPlaceholder: string;
    followUpPlaceholderShort: string;
    followUpSend: string;
    followUpQueuedChip: (n: number) => string;
    followUpQueuedItem: (content: string) => string;
    recallQueued: string;
    recallQueuedTitle: string;
    send: string;
    stop: string;
    compact: string;
    approve: string;
    deny: string;
    decisionAllow: string;
    decisionDeny: string;
    decisionManual: string;
    decisionAuto: string;
    decisionPolicy: string;
    thinking: string;
    subagent: string;
    subagentRunning: string;
    aborted: (item?: { errorCode?: string; errorMessage?: string; reason?: string }) => string;
    reconnect: (
      status: "retryable" | "failed" | "timeout" | "malformed",
      state: "waiting" | "retried" | "gaveUp",
      attempt: number,
      secondsLeft?: number,
      errorMessage?: string,
      errorCode?: string,
    ) => string;
    llmError: (errorMessage?: string) => string;
    reconnectRetryNow: string;
    reconnectGiveUp: string;
    imageAlt: string;
    toolImageAlt: string;
    imagesAsPathHint: string;
    infoPanel: string;
    sessionStats: string;
    sessionIdLabel: string;
    copySessionId: string;
    processList: string;
    processStop: string;
    processExited: string;
    processRemove: string;
    processRemoveHint: string;
    processClearExited: string;
    processClearExitedHint: string;
    statTokens: string;
    statTotalTokens: string;
    statCacheHit: (pct: string) => string;
    statElapsed: string;
    statElapsedSplit: (apiMs: string, toolMs: string) => string;
    statInput: string;
    statCached: string;
    statOutput: string;
    statTps: string;
    statParenOpen: string;
    statParenClose: string;
    noSessions: string;
    emptyStream: string;
    historyLoadFailed: string;
    statsLabel: string;
    removeImage: string;
    openAgents: string;
    workspacePanel: string;
    filesInMessage: (n: number) => string;
    imagesInMessage: (n: number) => string;
    openPreview: string;
    showMoreFiles: (n: number) => string;
    showLess: string;
    memoryChangesTitle: (n: number) => string;
    memoryScopeWorkspace: (key: string) => string;
    memoryOpWrite: string;
    memoryOpEdit: string;
    memoryViewTitle: string;
    memoryChangedMark: string;
    memoryContentUnavailable: string;
    memoryRowOpen: string;
    memoryOpenList: string;
    memoryBack: string;
    memoryEmptyAll: string;
    openAgentMemory: string;
    memoryShowMore: (n: number) => string;
    prevGroupPage: string;
    nextGroupPage: string;
    groupPagePosition: (page: number, total: number) => string;
    contextUsage: string;
    contextUnknown: string;
    contextComposition: string;
    contextPartSystemPrompt: string;
    contextPartToolDefs: string;
    contextPartUserMessages: string;
    contextPartAssistantMessages: string;
    contextPartToolRequests: string;
    contextPartToolResults: string;
    contextTopTools: string;
    contextWindowIs: (n: string) => string;
    contextTopToolsHint: string;
    contextTopFiles: string;
    contextTopFilesHint: string;
    contextRankLabel: string;
    contextRankTools: string;
    contextRankFiles: string;
    contextNoFileTraffic: string;
    contextUnknownHint: string;
    contextBreakdownEmpty: string;
    contextBreakdownFailed: string;
    contextThresholdCutter: string;
    contextThresholdHover: (n: string) => string;
    contextBeyondThreshold: string;
    contextThresholdTitle: string;
    contextThresholdBody: (agentName: string, old: string) => string;
    contextThresholdField: string;
    contextThresholdInvalid: string;
    contextThresholdCapped: (n: string) => string;
    contextThresholdSaved: (n: string) => string;
    contextWindowUnderThreshold: (n: string, m: string) => string;
    contextWindowUnderThresholdAction: string;
    contextWindowUnderThresholdDismiss: string;
    slashHint: string;
    switchAgent: string;
    switchAgentTitle: string;
    agentSearchPlaceholder: string;
    agentsNoMatch: string;
    handoffTargetTitle: (agent: string) => string;
    handoffRemove: string;
    skillsSelect: string;
    skillRemove: string;
    skillsSearchPlaceholder: string;
    skillsNoMatch: string;
    skillsEmptyHint: string;
    skillsAutoMessage: (names: string[]) => string;
    handoffFrom: (agent: string) => string;
    handoffBack: (title?: string) => string;
    switchModel: string;
    switchModelTitle: string;
    modelSwitchTargetTitle: (model: string) => string;
    modelSwitchRemove: string;
    modelSwitchBusyHint: string;
    modelSwitchFrom: (prevModel?: string) => string;
    modelSwitchAutoMessage: string;
    modelLockedHint: string;
    scheduledFrom: (name: string) => string;
    orgTriggerFrom: (org: string) => string;
    orgTriggerKinds: Record<string, string>;
    orgTriggerBudget: (budget: string) => string;
    backgroundDone: (
      kind: "command" | "subagent",
      status: "completed" | "failed" | "stopped",
    ) => string;
    emptyGreeting: string;
    mcpConnectTitle: string;
    mcpServerList: (servers: string[]) => string;
    mcpConnectResult: (toolCount: number, failed: string[]) => string;
    mcpToolsCount: (n: number) => string;
    mcpServerFailed: string;
    mcpConnectAborted: string;
    compactionTitle: (mode: string) => string;
    compactionRunning: (mode: string) => string;
    compactionDone: (mode: string) => string;
    compactionResult: string;
    compactionFailed: (status: string, errorMessage?: string) => string;
    unknownTool: string;
    toolAliases: Record<string, string>;
    workRunning: string;
    workDone: string;
    workGroupSteps: (n: number) => string;
    approvalWaiting: string;
    copyCode: string;
    copyReply: string;
    forkSession: string;
    forkSessionConfirmBody: string;
    forkSessionConfirmAction: string;
    forkSessionFailed: string;
    copyMessage: string;
    deleteSession: string;
    renameSession: string;
    renameSessionLabel: string;
    deleteSessionConfirm: (title: string) => string;
    draftGroup: string;
    draftUntitled: string;
    deleteDraft: string;
    deleteDraftConfirm: (title: string) => string;
    archiveSession: string;
    unarchiveSession: string;
    pinSession: string;
    unpinSession: string;
    pinnedSession: string;
    moreActions: string;
    loadMore: string;
    expandRestSessions: (n: number) => string;
    loadMoreSessions: string;
    folderGroups: {
      subagent: (n: number) => string;
      schedule: (n: number) => string;
      benchmark: (n: number) => string;
      archived: (n: number) => string;
    };
    folderOnlyGroup: (n: number, path?: string) => string;
    skillsBanner: (names: string[]) => string;
    attachedFilesBanner: (names: string[]) => string;
    plusMenu: string;
    uploadImage: string;
    uploadImageDesc: string;
    uploadFile: string;
    uploadFileDesc: string;
    removeFile: string;
    attachmentTooLarge: (name: string, limitMb: number) => string;
    dropFilesTitle: string;
    dropFilesDesc: string;
    dropFilesGoalHint: string;
    goalMode: string;
    goalModeDesc: string;
    goalBudgetLabel: string;
    goalBudgetUnlimited: string;
    goalBudgetValue: (value: string) => string;
    goalBudgetPlaceholder: string;
    goalBudgetHint: string;
    goalBudgetInvalid: string;
    goalBudgetSave: string;
    goalRemove: string;
    harnessInjected: string;
    goalProgress: (rounds: number, tokens: string) => string;
    goalStatus: Record<string, string>;
  };
  feishu: {
    intro: string;
    appId: string;
    appSecret: string;
    appSecretKeepHint: string;
    clearSecret: string;
    baseDomain: string;
    baseDomainHint: string;
    invalidDomain: string;
    testMessageNoChat: string;
    setupSteps: string[];
  };
  telegram: {
    intro: string;
    botToken: string;
    botTokenKeepHint: string;
    clearToken: string;
    openBotFather: string;
    invalidToken: string;
    testMessageNoChat: string;
    setupSteps: string[];
  };
  qq: {
    intro: string;
    appId: string;
    appSecret: string;
    appSecretKeepHint: string;
    clearSecret: string;
    testMessageNoChat: string;
    repliesOnly: string;
    replyBudget: string;
    scanStart: string;
    scanStarting: string;
    scanHint: string;
    scanQrLabel: string;
    scanWaiting: string;
    scanSteps: string;
    scanRefreshed: string;
    scanPrivacy: string;
    scanDone: (appId: string) => string;
    scanFailed: (reason: string) => string;
    scanExpiredRepeatedly: string;
    scanDisableFirst: string;
    scanOrManual: string;
    setupSteps: string[];
  };
  wechat: {
    intro: string;
    clearToken: string;
    scanOnly: string;
    testMessageNoChat: string;
    directOnly: string;
    media: string;
    scanStart: string;
    scanRescan: string;
    scanStarting: string;
    scanQrLabel: string;
    scanWaiting: string;
    scanSteps: string;
    scanScanned: string;
    scanRefreshed: string;
    scanPrivacy: string;
    scanDone: (botId: string) => string;
    scanFailed: (reason: string) => string;
    scanExpiredRepeatedly: string;
    scanBlocked: string;
    scanAlreadyBound: string;
    scanDisableFirst: string;
    verifyPrompt: string;
    verifyLabel: string;
    verifySubmit: string;
    verifySubmitting: string;
    setupSteps: string[];
  };
  messaging: {
    panelTitle: string;
    bindAction: string;
    dialogTitle: string;
    channelLabel: string;
    channelName: { feishu: string; telegram: string; qq: string; wechat: string };
    tutorial: string;
    console: string;
    enabled: string;
    bindByEnableHint: string;
    saveBeforeEnable: string;
    test: string;
    testing: string;
    testOk: (ms: number) => string;
    testOkAs: (account: string, ms: number) => string;
    testFail: (reason: string) => string;
    testPrivacyOn: string;
    sendTestMessage: string;
    sendingTestMessage: string;
    testMessageSent: string;
    statusLabel: string;
    status: { disconnected: string; connecting: string; connected: string; error: string };
    otherEnabledHint: (other: string) => string;
    credentialMissingHint: string;
    disableBeforeClearHint: string;
    renderMarkdown: string;
    renderMarkdownHelpFeishu: string;
    renderMarkdownHelpTelegram: string;
    renderMarkdownHelpQQ: string;
    renderMarkdownHelpWeChat: string;
    linePerMessage: string;
    linePerMessageHelp: string;
    finalReplyOnly: string;
    finalReplyOnlyHelp: string;
    finalReplyOnlyQQWarning: string;
    enabledIndicator: { feishu: string; telegram: string; qq: string; wechat: string };
    inboundLastAt: (when: string) => string;
    inboundNone: string;
    deliveryFailedInbound: (when: string, detail: string) => string;
    deliveryFailedSend: (when: string, detail: string) => string;
    lastConnectionError: (when: string, detail: string) => string;
    faqSetupTitle: string;
    faqWhatTitle: string;
    faqWhatBinding: string;
    faqTroubleTitle: string;
    troubleNoChat: string;
    troubleConnError: string;
    troubleOnePoller: string;
    troubleGroupPrivacy: string;
    troubleWeChatDirect: string;
    troubleQQPassive: string;
    troubleNoGroupInbound: string;
  };
  subagentPanel: {
    topologyLabel: string;
    mainSessionNote: string;
    empty: string;
    nodeRunning: string;
    nodeDone: string;
    openAsSession: string;
    subagentGone: string;
  };
  files: {
    title: string;
    upload: string;
    download: string;
    revealInFolder: string;
    copyPath: string;
    addToChat: string;
    addSelectionToChat: string;
    uploadHere: string;
    openInNewTab: string;
    previewNotIsolatedHint: string;
    refresh: string;
    root: string;
    empty: string;
    previewUnsupported: string;
    uploadedCount: (n: number) => string;
    uploading: (done: number, total: number) => string;
    uploadTooLarge: (names: string, mb: number) => string;
    folderDropSkipped: (names: string) => string;
    overwriteTitle: string;
    overwriteConfirm: (n: number) => string;
    loadFailed: string;
    previewTruncated: string;
    htmlRendered: string;
    htmlSource: string;
    backToList: string;
    treeLabel: string;
    showTree: string;
    hideTree: string;
    treeWidth: string;
    searchPlaceholder: string;
    searchClear: string;
    searchNoMatch: string;
    searching: string;
    searchTruncated: (n: number) => string;
    selectFile: string;
    dropToUpload: (dir: string) => string;
    editorLabel: (name: string) => string;
    wrapLines: string;
    unsaved: string;
    saveTitle: string;
    saveConfirmTitle: string;
    saveConfirm: (name: string) => string;
    editTooLarge: (kb: number) => string;
    saveTooLarge: (mb: number) => string;
    discardTitle: string;
    discardBody: (name: string) => string;
    discard: string;
    unsavedRestored: (name: string) => string;
    changedOnDisk: string;
    changedOnDiskHint: string;
    removeReference: string;
    renameTitle: string;
    renameLabel: string;
    renameHint: string;
    renameConfirm: string;
    renameTargetExists: (path: string) => string;
    renamed: (name: string) => string;
    deleteTitle: string;
    deleteBody: (name: string) => string;
    deleted: (name: string) => string;
    actionVersionReading: string;
    actionVersionFailed: string;
    changedBeforeAction: (name: string) => string;
    conflictTitle: string;
    conflictBody: (name: string) => string;
    overwriteAnyway: string;
  };
  usage: {
    title: string;
    today: string;
    last7d: string;
    total: string;
    tokens: string;
    requests: string;
    from: string;
    to: string;
    colCacheRead: string;
    colCacheWrite: string;
    colOutput: string;
    uncostedNote: string;
    filterAllAgents: string;
    filterAllModels: string;
    rangeLabel: string;
    rangeHour: string;
    rangeDay: string;
    range7d: string;
    range30d: string;
    range90d: string;
    rangeCustom: string;
    chartRequestsByAgent: string;
    chartRequestsByModel: string;
    legendSuccessRate: string;
    chartTokenTrend: string;
    chartCostTrend: string;
    legendOther: (n: number) => string;
    bucketTotal: string;
    legendHitRate: string;
    empty: string;
    errors: string;
    errorsTotal: string;
    errorsUnexpected: string;
    errorsExpected: string;
    errorsTopCode: string;
    errorsColCode: string;
    errorsColKind: string;
    errorsColMessage: string;
    errorsEmpty: string;
    errorsNewer: string;
    errorsOlder: string;
    errorsPageOf: (page: number, pages: number, total: number) => string;
    errorsClear: string;
    errorsClearTitle: string;
    errorsClearRangePreset: (preset: "1h" | "1d" | "7d" | "30d" | "90d") => string;
    errorsClearRangeCustom: (from: string, to: string) => string;
    errorsClearScope: (count: number, range: string) => string;
    errorsClearScopeAgent: (count: number, range: string, agentId: string) => string;
    errorsClearIrreversible: string;
    errorsClearDone: (count: number) => string;
  };
  traces: {
    timeline: string;
    laneLLM: string;
    kindThinking: string;
    kindModelReply: string;
    kindToolGen: string;
    legendToolExec: string;
    legendOther: string;
    toolParams: string;
    requiredParam: string;
    legendApprovalWait: string;
    task: (n: number) => string;
    globalSummary: string;
    tasksLabel: string;
    messages: string;
    loadingNote: (shown: number, total: number) => string;
    zoom: string;
    zoomReset: string;
    zoomOut: string;
    zoomIn: string;
    linkHint: string;
    filesTitle: string;
    toolCalls: string;
    taskInput: string;
    taskOutput: string;
    cacheHit: string;
    hitRate: string;
    avgToolCalls: string;
    inProgress: string;
    systemPrompt: string;
    toolDefs: (n: number) => string;
    exportFile: string;
  };
  benchmark: {
    title: string;
    guideFlow: { title: string; text: string }[];
    guideCreateMember: string;
    searchPlaceholder: string;
    noMatches: string;
    filterByAgent: (agentId: string) => string;
    clearFilter: string;
    emptyTitle: string;
    emptyDescription: string;
    caseCount: (n: number) => string;
    runsPerCase: (n: number) => string;
    notEvaluated: string;
    building: string;
    buildingHint: string;
    buildingDetail: string;
    creationFailed: string;
    creationFailedHint: string;
    creationFailedDetail: string;
    creationFailedHintMember: string;
    creationFailedDetailMember: string;
    testedAgents: string;
    lastEvaluated: (when: string) => string;
    sparklineLabel: (n: number) => string;
    latestScoreLabel: string;
    firstEvaluation: string;
    use: string;
    evaluate: string;
    optimize: string;
    view: string;
    copyPath: string;
    deleteBenchmark: string;
    deleteConfirm: (title: string) => string;
    deleted: string;
    backToList: string;
    notFound: string;
    notFoundHint: string;
    trendTitle: (metric: string) => string;
    cases: string;
    viewCase: string;
    taskMaterials: string;
    rubric: string;
    agentHidden: string;
    caseFileUnavailable: string;
    evaluations: string;
    noEvaluations: string;
    noEvaluationsHint: string;
    summaryLabel: string;
    unlabeled: string;
    agentColumn: string;
    colVersion: string;
    colModel: string;
    colThinkingLevel: string;
    colScore: string;
    colDuration: string;
    colCase: string;
    colRun: string;
    colSession: string;
    askAi: string;
    evaluationDetailTitle: (time: string) => string;
    askEvaluationTitle: string;
    askEvaluationDescription: string;
    askEvaluationDefault: string;
    askEvaluationExamples: {
      explain: { label: string; prompt: string };
      whyLow: { label: string; prompt: string };
      weakest: { label: string; prompt: string };
      againstPrevious: { label: string; prompt: string };
    };
    askEvaluationTail: (p: {
      benchmarkId: string;
      time: string;
      label: string;
      version: number;
      provider: string;
      modelId: string;
      thinkingLevel: string;
      score: string;
      cost: string;
      duration: string;
      summaryTitle: string;
      summary: string;
      cases: { id: string; score: string; cost: string; duration: string; sessionIds: string[] }[];
    }) => string;
    askCaseTitle: string;
    askCaseDescription: string;
    askCaseDefault: string;
    askCaseExamples: {
      explain: { label: string; prompt: string };
      rubricRewards: { label: string; prompt: string };
      whyRunLow: { label: string; prompt: string };
      clearerStatement: { label: string; prompt: string };
    };
    askCaseTail: (p: {
      benchmarkId: string;
      caseId: string;
      latest: { time: string; score: string; runs: { score: string; sessionId: string }[] } | null;
    }) => string;
    aiCreateTitle: string;
    aiCreateDescription: string;
    targetAgent: string;
    targetAgentHint: string;
    aiCreateExamples: {
      decisionAgent: { label: string; description: string; prompt: string };
      reportWriter: { label: string; description: string; prompt: string };
      customerService: { label: string; description: string; prompt: string };
      codeReview: { label: string; description: string; prompt: string };
    };
    aiCreateTail: (targetAgentId: string) => string;
    manualCreateTitle: string;
    manualCreateIntro: string;
    idField: string;
    idHint: string;
    idGenerateHint: string;
    idExists: string;
    titleField: string;
    descriptionField: string;
    descriptionHint: string;
    runsField: string;
    runsHint: string;
    runsInfo: string;
    casesTitle: string;
    casesInfo: string;
    rubricInfo: string;
    caseHeading: (n: number) => string;
    caseSlugField: string;
    caseSlugHint: (id: string) => string;
    caseTitleField: string;
    caseStatementField: string;
    caseStatementHint: string;
    caseRubricField: string;
    caseRubricHint: string;
    addCase: string;
    removeCase: string;
    createSubmit: string;
    created: string;
    invalidId: string;
    invalidRuns: string;
    invalidScore: string;
    useTitle: (title: string) => string;
    testedAgent: string;
    evaluateDescription: string;
    evaluateTestedAgentHint: string;
    evaluatorAgent: string;
    evaluatorAgentHint: string;
    evaluatorMissingSkill: string;
    evaluateSessionModel: string;
    evaluateSessionModelHint: string;
    evaluateRunsHint: string;
    evaluateNoteField: string;
    evaluateNotePlaceholder: string;
    evaluateTail: (p: { targetAgentId: string; benchmarkId: string; runs: number }) => string;
    optimizeDescription: string;
    optimizerAgent: string;
    optimizerAgentHint: string;
    optimizerMissingSkill: string;
    testedAgentHint: string;
    sessionModel: string;
    sessionModelHint: string;
    optimizeRunsHint: string;
    roundLimitField: string;
    roundLimitHint: string;
    targetScoreField: string;
    targetScoreHint: string;
    focusField: string;
    focusPlaceholder: string;
    noBaseline: string;
    baselineLine: (score: string, target: number) => string;
    optimizeTail: (p: {
      targetAgentId: string;
      benchmarkId: string;
      runs: number;
      roundLimit: number;
      targetScore: number;
    }) => string;
  };
  company: {
    workMode: string;
    modeDev: string;
    modeCompany: string;
    switchToCompany: string;
    switchToDev: string;
    beta: string;
    betaTitle: string;
    betaNotice: string;
    switcher: string;
    noOrganizations: string;
    createOrg: string;
    orgSettings: string;
    orgInvalid: string;
    orgPaused: string;
    switcherCurrent: string;
    inProject: (project: string, org: string) => string;
    landingTitle: string;
    landingBody: string;
    orgGoneTitle: string;
    orgGoneBody: string;
    backToOrgs: string;
    createTitle: string;
    orgId: string;
    orgIdHint: string;
    displayName: string;
    displayNameHint: string;
    mission: string;
    missionHint: string;
    missionPlaceholder: string;
    missionExampleHint: string;
    missionExamples: {
      research: { name: string; mission: string };
      agentTuning: { name: string; mission: string };
      cloudReseller: { name: string; mission: string };
      mirror: { name: string; mission: string };
    };
    createdOpeningCeo: string;
    modelField: string;
    modelInfo: string;
    modelHint: string;
    modelClear: string;
    modelStale: string;
    modelProjectDefault: string;
    modelProjectDefaultNamed: (name: string) => string;
    modelsLoadFailed: string;
    workspaceField: string;
    workspaceInfo: string;
    workspaceHint: string;
    workspaceEmpty: string;
    workspaceMenuHint: string;
    workspaceClear: string;
    ceoBudget: string;
    ceoBudgetHint: string;
    draftRestored: string;
    clearDraft: string;
    creating: string;
    settingsTitle: string;
    timezone: string;
    timezoneHint: string;
    language: string;
    languageInfo: string;
    languages: { zh: string; en: string };
    approvalMode: string;
    approvalModeInfo: string;
    approvalModes: Record<string, string>;
    status: string;
    statusActive: string;
    statusPaused: string;
    pause: string;
    resume: string;
    pauseInfo: string;
    settingsLoadFailed: string;
    employeeStates: Record<string, string>;
    ceo: string;
    reportsTo: (name: string) => string;
    openDesk: string;
    openingDesk: string;
    principalSystem: string;
    principalAll: string;
    spendOfBudget: (spend: string, budget: string) => string;
    noBudget: string;
    budgetUnit: (symbol: string) => string;
    budgetStoredAs: (amount: string) => string;
    sessionList: {
      desks: (n: number) => string;
      deskOf: (name: string) => string;
      running: string;
      noEmployees: string;
      untitledSession: string;
      loadFailed: string;
    };
    overview: {
      title: string;
      info: string;
      employees: string;
      onDesk: string;
      running: string;
      paused: string;
      board: string;
      blocked: string;
      today: string;
      todayEmpty: string;
      spend: string;
      reviewTickets: string;
      alerts: string;
      alertsEmpty: string;
      firstStep: string;
      createdBy: (user: string) => string;
      employeesCount: (n: number) => string;
      period: (period: string) => string;
      openCeoDesk: string;
      refreshFailed: string;
      mission: string;
      expand: string;
      collapse: string;
      openTickets: string;
      boardTotal: (n: number) => string;
      todayCount: (n: number) => string;
      upcoming: string;
      failed: string;
      budgetLeft: (amount: string) => string;
      overBudget: (amount: string) => string;
      openChart: string;
      openBoard: string;
      openCalendar: string;
      openFinance: string;
      openTicket: string;
      openChannel: string;
      openColumn: (column: string) => string;
      firstStepsTitle: string;
      firstStepsInfo: string;
      stepCeoTitle: string;
      stepCeoBody: string;
      stepHireTitle: string;
      stepHireBody: string;
      stepScheduleTitle: string;
      stepScheduleBody: string;
      stepDone: string;
      goToChart: string;
      goToCalendar: string;
      inbox: string;
      inboxInfo: string;
      inboxEmpty: string;
      inboxFilters: { all: string; mention: string; blocked: string; done: string };
      inboxCategories: { mention: string; blocked: string; done: string };
      timelineMore: (n: number) => string;
    };
    calendarOutcomes: Record<string, string>;
    chart: {
      title: string;
      info: string;
      empty: string;
      nodeMenu: string;
      hire: string;
      setBudget: string;
      changeReportsTo: string;
      renewDesk: string;
      leave: string;
      ceoCannotLeave: string;
      invalidEntry: string;
      workspaceTail: string;
      hireTitle: (manager: string) => string;
      hireSource: string;
      hireExisting: string;
      hireNew: string;
      agent: string;
      pickAgent: string;
      noAgentsLeft: string;
      agentId: string;
      agentIdHint: string;
      agentName: string;
      agentNameHint: string;
      agentDescription: string;
      plugins: string;
      pluginsHint: string;
      pluginsPlaceholder: string;
      pluginsPicked: (n: number) => string;
      pluginsEmpty: string;
      employeeTitle: string;
      employeeTitlePlaceholder: string;
      duties: string;
      dutiesHint: string;
      workspace: string;
      workspaceHint: string;
      hireWorkspaceHint: string;
      budget: string;
      budgetHint: string;
      hireConfirm: (name: string, manager: string) => string;
      hired: (name: string) => string;
      budgetTitle: (name: string) => string;
      budgetConfirm: (name: string, budget: string) => string;
      reportsToTitle: (name: string) => string;
      reportsToConfirm: (name: string, manager: string) => string;
      reportsToCycle: string;
      renewDeskTitle: (name: string) => string;
      renewDeskExplain: string;
      workspaceInvalid: string;
      renewed: string;
      leaveConfirm: (name: string) => string;
      left: (name: string) => string;
      saved: string;
      canvas: string;
      zoom: string;
      zoomIn: string;
      zoomOut: string;
      zoomFit: string;
      legend: string;
      employeeCount: (n: number) => string;
      spend: string;
      refreshFailed: (error: string) => string;
      detached: string;
      detachedNotice: (n: number) => string;
      hireAgentSection: string;
      hirePositionSection: string;
      agentHint: string;
      budgetPlaceholder: string;
      clearBudget: string;
      currentValue: (value: string) => string;
      manager: string;
      reportsToHint: string;
    };
    calendar: {
      title: string;
      info: string;
      month: string;
      week: string;
      day: string;
      today: string;
      prev: string;
      next: string;
      allEmployees: string;
      filterEmployee: string;
      create: string;
      createTitle: string;
      editTitle: (name: string) => string;
      employee: string;
      name: string;
      nameHint: string;
      prompt: string;
      enabled: string;
      startAt: string;
      endAt: string;
      period: string;
      periodHint: string;
      delete: string;
      deleteConfirm: (name: string) => string;
      saveConfirm: (name: string) => string;
      outcome: string;
      lastFired: string;
      nextFire: string;
      past: string;
      pausedNote: string;
      disabledNote: string;
      invalidFiles: string;
      empty: string;
      emptyHint: string;
      moreEvents: (n: number) => string;
      moreEventsExpand: (n: number) => string;
      openDay: string;
      weekdays: readonly string[];
      allDay: string;
      promptHint: string;
      monthTitle: (year: number, month: number) => string;
      cadence: {
        once: string;
        minutes: (n: number) => string;
        hours: (n: number) => string;
        daily: (time: string) => string;
        days: (n: number, time: string) => string;
        weekly: (time: string) => string;
        weeks: (n: number, time: string) => string;
        invalid: string;
      };
      legendEmpty: string;
      legendFilter: (name: string) => string;
      createAt: (label: string) => string;
      loadFailed: (error: string) => string;
      dismissHint: string;
      staggerHint: string;
      warningsPrefix: string;
    };
    tickets: {
      title: string;
      info: string;
      columns: Record<string, string>;
      blockedOnly: string;
      create: string;
      createTitle: string;
      empty: string;
      emptyHint: string;
      dismissHint: string;
      columnEmpty: string;
      ticketTitle: string;
      goal: string;
      goalHint: string;
      acceptance: string;
      acceptanceHint: string;
      result: string;
      owner: string;
      noOwner: string;
      ownerSelf: string;
      ownerSelfHint: string;
      parent: string;
      noParent: string;
      notify: string;
      notifyHint: string;
      priority: string;
      due: string;
      noDue: string;
      blocked: string;
      blockedReason: string;
      blockedBy: string;
      blockedTooltip: (reason: string, by: string) => string;
      unblock: string;
      unblockConfirm: (title: string) => string;
      block: string;
      blockTitle: string;
      blockReasonHint: string;
      blockByHint: string;
      sessions: string;
      sessionsCount: (n: number) => string;
      openSession: string;
      openTicket: string;
      progress: string;
      progressEmpty: string;
      addProgress: string;
      progressPlaceholder: string;
      children: string;
      childrenEmpty: string;
      cost: string;
      rolledUpCost: string;
      parentLine: (title: string) => string;
      moveTitle: string;
      moveConfirm: (title: string, column: string) => string;
      rejectReason: string;
      rejectReasonHint: string;
      moved: string;
      invalid: string;
      invalidFiles: string;
      edit: string;
      saveConfirm: (title: string) => string;
      saved: string;
      created: string;
      detail: string;
      back: string;
      dragHint: string;
      searchPlaceholder: string;
      searchNoMatch: string;
      dropHere: string;
      overdue: string;
      summary: string;
      history: string;
      historyEmpty: string;
      historyActions: Record<string, string>;
      slug: string;
      slugHint: string;
      slugInvalid: string;
      noGoal: string;
      noAcceptance: string;
      noResult: string;
      moveTo: string;
      move: string;
      copyId: string;
      invalidTickets: string;
      loadFailed: (error: string) => string;
    };
    finance: {
      title: string;
      info: string;
      period: string;
      thisPeriod: string;
      prevPeriod: string;
      total: string;
      unpriced: string;
      budget: string;
      editBudget: string;
      budgetPlaceholder: string;
      clearBudget: string;
      budgetSaved: string;
      own: string;
      cumulative: string;
      cumulativeBudget: string;
      ratio: string;
      warned: string;
      paused: string;
      spendTree: string;
      spendTreeInfo: string;
      ticketsTable: string;
      ticketsInfo: string;
      ticketsEmpty: string;
      rolledUp: string;
      expandChildren: string;
      collapseChildren: string;
      childCount: (n: number) => string;
      trend: string;
      alerts: string;
      alertsEmpty: string;
      alertWarned: (name: string, at: string) => string;
      alertPaused: (name: string, at: string) => string;
      alertsHint: string;
      kpiTotal: string;
      orgBudget: string;
      kpiEmployees: string;
      budgetsSet: (n: number) => string;
      thresholds: string;
      kpiAlerts: string;
      alertsSummary: (warned: number, paused: number) => string;
      cumulativeInfo: string;
      rolledUpInfo: string;
      root: string;
      budgetEmptyHint: string;
      saveBudget: string;
      cancelEdit: string;
      editBudgetOf: (name: string) => string;
      openTicket: string;
      trendInfo: string;
      trendEmpty: string;
      alertsInfo: string;
      pausedGroup: string;
      warnedGroup: string;
      warnedAt: (at: string) => string;
      pausedAt: (at: string) => string;
      refreshFailed: string;
    };
    channels: {
      listTitle: string;
      drawerLabel: string;
      allHands: string;
      mine: string;
      others: string;
      archivedGroup: string;
      newChannel: string;
      noChannels: string;
      loadFailed: string;
      join: string;
      joining: string;
      joined: string;
      joinTitle: string;
      joinConfirm: string;
      mentionChip: string;
      badgeUnread: (n: number) => string;
      badgeMentions: (n: number) => string;
      streamLabel: (name: string) => string;
      purpose: string;
      purposeEmpty: string;
      memberCount: (n: number) => string;
      memberList: string;
      invite: string;
      inviteTitle: string;
      inviteSearch: string;
      inviteEmpty: string;
      invited: (name: string) => string;
      leave: string;
      leaveTitle: string;
      leaveConfirm: (name: string) => string;
      left: string;
      channelMenu: string;
      rename: string;
      renameTitle: string;
      editPurpose: string;
      purposeTitle: string;
      archive: string;
      unarchive: string;
      archiveTitle: string;
      archiveConfirm: (name: string) => string;
      archived: string;
      unarchived: string;
      archivedNotice: string;
      notMemberNotice: string;
      channelLoadFailed: string;
      allHandsInfo: string;
      channelInfo: string;
      allHandsNoArchive: string;
      createTitle: string;
      creating: string;
      created: string;
      idField: string;
      idHint: string;
      idReserved: string;
      idTaken: string;
      nameField: string;
      nameHint: string;
      purposeHint: string;
      empty: string;
      emptyHint: string;
      placeholder: string;
      send: string;
      you: string;
      mentionAll: string;
      mentionAllDesc: string;
      employees: string;
      members: string;
      earlierDays: string;
      ticketRef: (id: string) => string;
      sessionRef: string;
      replyTo: string;
      openTicketRef: string;
      replyToJump: string;
      hop: (n: number) => string;
      hopInfo: string;
      hopSummary: string;
      today: string;
      yesterday: string;
      noEarlier: string;
      unreadDivider: string;
      newMessages: (n: number) => string;
      mentionPanel: string;
      mentionsYou: string;
      systemMessage: string;
      sentAt: (time: string) => string;
      notices: {
        employee_joined: (agent: string, title: string, manager: string) => string;
        employee_left: (agent: string, manager: string) => string;
        channel_created: (by: string) => string;
        channel_archived: (by: string) => string;
        channel_unarchived: (by: string) => string;
        channel_joined: (principal: string) => string;
        channel_invited: (by: string, principal: string) => string;
        channel_left: (principal: string) => string;
        channel_removed: (by: string, principal: string) => string;
        budget_warned: (
          agent: string,
          percent: string,
          period: string,
          cost: string,
          budget: string,
        ) => string;
        budget_paused: (
          agent: string,
          percent: string,
          period: string,
          cost: string,
          budget: string,
        ) => string;
        ticket_blocked: (ticket: string, title: string) => string;
        ticket_done: (ticket: string, title: string) => string;
        ticket_rejected: (ticket: string, title: string) => string;
      };
    };
    handbook: {
      info: string;
      indexLabel: string;
      documents: string;
      collapseAll: string;
      documentsInFolder: (n: number) => string;
      noOtherDocuments: string;
      emptyDocument: string;
      newDocument: string;
      creating: string;
      pathField: string;
      pathPlaceholder: string;
      pathHint: string;
      pathInvalid: string;
      pathExists: string;
      documentCreated: string;
      deleteDocument: string;
      deleteConfirm: (path: string) => string;
      documentDeleted: string;
      loadFailed: string;
      documentLoadFailed: string;
      updatedAt: (time: string, size: string) => string;
      editorHint: string;
    };
  };
  errors: {
    networkError: string;
    modelCredentialMissing: (modelId: string) => string;
    noDefaultModel: string;
    byCode: {
      activity_invalid: string;
      activity_exists: string;
      activity_not_found: string;
      activity_stopping: string;
      collection_not_found: string;
      draft_conflict: string;
      spec_invalid: string;
      description_required: string;
      generation_running: string;
      module_spec_required: string;
      media_invalid: string;
      media_stale: string;
      speech_credential_missing: string;
      speech_helper_missing: string;
      audio_invalid: string;
      audio_changed: string;
      media_missing: string;
      module_spec_invalid: string;
      waf_checkout_missing: string;
      run_not_found: string;
      project_deleting: string;
      invalid_credentials: string;
      too_many_attempts: string;
      password_mismatch: string;
      invalid_password: string;
      admin_required: string;
      desktop_single_user: string;
      not_found: string;
      internal: string;
      agent_not_found: string;
      unknown_agent: string;
      agent_exists: string;
      agent_deleting: string;
      project_exists: string;
      project_not_found: string;
      cannot_delete_last_project: string;
      user_exists: string;
      user_not_found: string;
      cannot_delete_admin: string;
      member_not_found: string;
      already_member: string;
      already_owner: string;
      memory_import_confirm_required: string;
      schedule_exists: string;
      schedule_not_found: string;
      unknown_skill: string;
      unknown_plugin: string;
      goal_plugin_not_installed: string;
      skill_too_large: string;
      hook_too_large: string;
      file_not_found: string;
      not_pending: string;
      follow_up_started: string;
      file_too_large: string;
      too_many_files: string;
      payload_too_large: string;
      image_too_large: string;
      dir_not_absolute: string;
      dir_not_found: string;
      not_a_dir: string;
      path_not_found: string;
      reveal_failed: string;
      workspace_missing: string;
      workspace_not_found: string;
      session_not_found: string;
      session_deleting: string;
      approval_not_found: string;
      process_not_found: string;
      process_running: string;
      memory_file_not_found: string;
      memory_scope_not_found: string;
      task_in_progress: string;
      compacting: string;
      shutting_down: string;
      platform_rate_limited: string;
      compaction_not_configured: string;
      nothing_to_compact: string;
      already_compacted: string;
      version_conflict: string;
      invalid_title: string;
      invalid_proxy_url: string;
      invalid_attachment_limit: string;
      invalid_trace: string;
      trace_not_found: string;
      trace_session_exists: string;
      feishu_secret_required: string;
      feishu_not_bound: string;
      feishu_no_chat: string;
      feishu_send_failed: string;
      telegram_token_required: string;
      telegram_token_invalid: string;
      telegram_not_bound: string;
      telegram_no_chat: string;
      telegram_send_failed: string;
      another_channel_enabled: string;
      account_enabled_elsewhere: string;
      messaging_disable_before_clear: string;
      messaging_disable_before_scan: string;
      company_mode_off: string;
      org_not_found: string;
      org_exists: string;
      org_invalid: string;
      invalid_org_id: string;
      employee_not_found: string;
      employee_exists: string;
      calendar_event_exists: string;
      calendar_event_not_found: string;
      desk_unavailable: string;
      ticket_not_found: string;
      ticket_invalid: string;
      ticket_session_failed: string;
      handbook_file_not_found: string;
      handbook_index_required: string;
    };
  };
};
